# https://taskfile.dev

version: '3'

vars:
  GENERATOR: "go"
  BUNDLEDSPEC: "oapigen/.api/bundled.yaml"
  GENERATORCONFIG: "oapigen/.openapi-generator/go/config-client-go.yaml"
  GENERATORIGNOREFILE: "oapigen/.openapi-generator/.openapi-generator-ignore"
  TEMPLATEDIR: "oapigen/.openapi-generator/go/templates"
  SPECREPO: "https://github.com/gomorpheus/morpheus-openapi"
  OUTPUTDIR: "oapigen/sdk"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install-redocly:
    internal: true
    cmds:
      - npm i -g @redocly/cli@1.34.3
  
  install-openapi-generator:
    internal: true
    cmds:
      - npm install @openapitools/openapi-generator-cli -g
      - openapi-generator-cli version-manager set 7.12.0
  
  install-goimports:
    internal: true
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  # perform tooling installations in parallel
  install-tools:
    desc: install redocly, openapi-generator, goimports
    deps: [install-redocly, install-openapi-generator, install-goimports]

  generate:
    desc: generate a Go SDK from the local OpenAPI spec
    env:
      _JAVA_OPTIONS: -DmaxYamlCodePoints=99999999
    cmds:
      - rm -rf {{.OUTPUTDIR}}
      - mkdir -p {{.OUTPUTDIR}}
      - cp {{.GENERATORIGNOREFILE}} {{.OUTPUTDIR}}
      - cmd: >-
          openapi-generator-cli generate 
          --inline-schema-options SKIP_SCHEMA_REUSE=true
          -g {{.GENERATOR}}
          -i {{.BUNDLEDSPEC}}
          -c {{.GENERATORCONFIG}}
          {{if .TEMPLATEDIR -}}-t {{.TEMPLATEDIR}} {{end}}
          -o {{.OUTPUTDIR}}
      - goimports -w ./oapigen
  
  clone-spec:
    silent: true
    internal: true
    cmds:
      - git clone {{.SPECREPO}}

  bundle-spec:
    internal: true
    cmds:
      - defer: rm -f pathsTmp.yaml
      - >-
        yq '(load("includePaths.yaml") | .includePaths) as $p | .paths[] | select(key == $p[]) | {key: .}'
        morpheus-openapi/openapi.yaml > pathsTmp.yaml
      - >-
        yq -i '.paths = load("pathsTmp.yaml")' morpheus-openapi/openapi.yaml
      - >-
        redocly bundle 
        --dereferenced 
        --output {{.BUNDLEDSPEC}}
        morpheus-openapi/openapi.yaml

  update-spec-local:
    desc: "update OpenAPI spec to match parallel local morpheus-openapi repo"
    vars:
      GITREF: '{{if (empty .GITREF)}}tf-dev{{else}}{{.GITREF}}{{end}}'
    dir: morpheus-openapi
    cmds:
      - git clone ../../morpheus-openapi .
      - defer: rm -rf ../morpheus-openapi
      - git checkout {{.GITREF}}
      - task: bundle-spec
  
  update-spec:
    desc: "update OpenAPI spec to match the morpheus-openapi GITREF"
    vars:
      GITREF: '{{if (empty .GITREF)}}tf-dev{{else}}{{.GITREF}}{{end}}'
    dir: morpheus-openapi
    cmds:
      - task: clone-spec
      - defer: rm -rf ../morpheus-openapi
      - git checkout {{.GITREF}}
      - task: bundle-spec
      - git rev-parse HEAD > ../oapigen/.api/latest-commit-sha
  
  update-client:
    desc: "update Go SDK to match the morpheus-openapi GITREF"
    cmds:
      - task: update-spec
      - task: generate
