/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddClouds200ResponseAllOfZoneConfigAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddClouds200ResponseAllOfZoneConfigAnyOf{}

// AddClouds200ResponseAllOfZoneConfigAnyOf struct for AddClouds200ResponseAllOfZoneConfigAnyOf
type AddClouds200ResponseAllOfZoneConfigAnyOf struct {
	ApplianceUrl               NullableString                                         `json:"applianceUrl,omitempty"`
	DatacenterName             NullableString                                         `json:"datacenterName,omitempty"`
	ExternalId                 NullableString                                         `json:"externalId,omitempty"`
	InventoryLevel             NullableString                                         `json:"inventoryLevel,omitempty"`
	ConsoleKeymap              NullableString                                         `json:"consoleKeymap,omitempty"`
	BackupMode                 NullableString                                         `json:"backupMode,omitempty"`
	CertificateProvider        NullableString                                         `json:"certificateProvider,omitempty"`
	ConfigCmdbDiscovery        *bool                                                  `json:"configCmdbDiscovery,omitempty"`
	EnableNetworkTypeSelection NullableString                                         `json:"enableNetworkTypeSelection,omitempty"`
	KubeUrl                    NullableString                                         `json:"kubeUrl,omitempty"`
	NetworkServer              *AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer `json:"networkServer,omitempty"`
	NetworkServerId            *string                                                `json:"networkServer.id,omitempty"`
	ReplicationMode            NullableString                                         `json:"replicationMode,omitempty"`
	SecurityServer             NullableString                                         `json:"securityServer,omitempty"`
	AdditionalProperties       map[string]interface{}                                 `json:",remain"`
}

type _AddClouds200ResponseAllOfZoneConfigAnyOf AddClouds200ResponseAllOfZoneConfigAnyOf

// NewAddClouds200ResponseAllOfZoneConfigAnyOf instantiates a new AddClouds200ResponseAllOfZoneConfigAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddClouds200ResponseAllOfZoneConfigAnyOf() *AddClouds200ResponseAllOfZoneConfigAnyOf {
	this := AddClouds200ResponseAllOfZoneConfigAnyOf{}
	return &this
}

// NewAddClouds200ResponseAllOfZoneConfigAnyOfWithDefaults instantiates a new AddClouds200ResponseAllOfZoneConfigAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddClouds200ResponseAllOfZoneConfigAnyOfWithDefaults() *AddClouds200ResponseAllOfZoneConfigAnyOf {
	this := AddClouds200ResponseAllOfZoneConfigAnyOf{}
	return &this
}

// GetApplianceUrl returns the ApplianceUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetApplianceUrl() string {
	if o == nil || IsNil(o.ApplianceUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ApplianceUrl.Get()
}

// GetApplianceUrlOk returns a tuple with the ApplianceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetApplianceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplianceUrl.Get(), o.ApplianceUrl.IsSet()
}

// IsSetApplianceUrl returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetApplianceUrl() bool {
	if o != nil && o.ApplianceUrl.IsSet() {
		return true
	}

	return false
}

// SetApplianceUrl gets a reference to the given NullableString and assigns it to the ApplianceUrl field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetApplianceUrl(v string) {
	o.ApplianceUrl.Set(&v)
}

// SetApplianceUrlNil sets the value for ApplianceUrl to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetApplianceUrlNil() {
	o.ApplianceUrl.Set(nil)
}

// UnsetApplianceUrl ensures that no value is present for ApplianceUrl, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetApplianceUrl() {
	o.ApplianceUrl.Unset()
}

// GetDatacenterName returns the DatacenterName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetDatacenterName() string {
	if o == nil || IsNil(o.DatacenterName.Get()) {
		var ret string
		return ret
	}
	return *o.DatacenterName.Get()
}

// GetDatacenterNameOk returns a tuple with the DatacenterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetDatacenterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatacenterName.Get(), o.DatacenterName.IsSet()
}

// IsSetDatacenterName returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetDatacenterName() bool {
	if o != nil && o.DatacenterName.IsSet() {
		return true
	}

	return false
}

// SetDatacenterName gets a reference to the given NullableString and assigns it to the DatacenterName field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetDatacenterName(v string) {
	o.DatacenterName.Set(&v)
}

// SetDatacenterNameNil sets the value for DatacenterName to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetDatacenterNameNil() {
	o.DatacenterName.Set(nil)
}

// UnsetDatacenterName ensures that no value is present for DatacenterName, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetDatacenterName() {
	o.DatacenterName.Unset()
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// IsSetExternalId returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}

// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetInventoryLevel returns the InventoryLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetInventoryLevel() string {
	if o == nil || IsNil(o.InventoryLevel.Get()) {
		var ret string
		return ret
	}
	return *o.InventoryLevel.Get()
}

// GetInventoryLevelOk returns a tuple with the InventoryLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetInventoryLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InventoryLevel.Get(), o.InventoryLevel.IsSet()
}

// IsSetInventoryLevel returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetInventoryLevel() bool {
	if o != nil && o.InventoryLevel.IsSet() {
		return true
	}

	return false
}

// SetInventoryLevel gets a reference to the given NullableString and assigns it to the InventoryLevel field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetInventoryLevel(v string) {
	o.InventoryLevel.Set(&v)
}

// SetInventoryLevelNil sets the value for InventoryLevel to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetInventoryLevelNil() {
	o.InventoryLevel.Set(nil)
}

// UnsetInventoryLevel ensures that no value is present for InventoryLevel, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetInventoryLevel() {
	o.InventoryLevel.Unset()
}

// GetConsoleKeymap returns the ConsoleKeymap field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetConsoleKeymap() string {
	if o == nil || IsNil(o.ConsoleKeymap.Get()) {
		var ret string
		return ret
	}
	return *o.ConsoleKeymap.Get()
}

// GetConsoleKeymapOk returns a tuple with the ConsoleKeymap field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetConsoleKeymapOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConsoleKeymap.Get(), o.ConsoleKeymap.IsSet()
}

// IsSetConsoleKeymap returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetConsoleKeymap() bool {
	if o != nil && o.ConsoleKeymap.IsSet() {
		return true
	}

	return false
}

// SetConsoleKeymap gets a reference to the given NullableString and assigns it to the ConsoleKeymap field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetConsoleKeymap(v string) {
	o.ConsoleKeymap.Set(&v)
}

// SetConsoleKeymapNil sets the value for ConsoleKeymap to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetConsoleKeymapNil() {
	o.ConsoleKeymap.Set(nil)
}

// UnsetConsoleKeymap ensures that no value is present for ConsoleKeymap, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetConsoleKeymap() {
	o.ConsoleKeymap.Unset()
}

// GetBackupMode returns the BackupMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetBackupMode() string {
	if o == nil || IsNil(o.BackupMode.Get()) {
		var ret string
		return ret
	}
	return *o.BackupMode.Get()
}

// GetBackupModeOk returns a tuple with the BackupMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetBackupModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupMode.Get(), o.BackupMode.IsSet()
}

// IsSetBackupMode returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetBackupMode() bool {
	if o != nil && o.BackupMode.IsSet() {
		return true
	}

	return false
}

// SetBackupMode gets a reference to the given NullableString and assigns it to the BackupMode field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetBackupMode(v string) {
	o.BackupMode.Set(&v)
}

// SetBackupModeNil sets the value for BackupMode to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetBackupModeNil() {
	o.BackupMode.Set(nil)
}

// UnsetBackupMode ensures that no value is present for BackupMode, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetBackupMode() {
	o.BackupMode.Unset()
}

// GetCertificateProvider returns the CertificateProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetCertificateProvider() string {
	if o == nil || IsNil(o.CertificateProvider.Get()) {
		var ret string
		return ret
	}
	return *o.CertificateProvider.Get()
}

// GetCertificateProviderOk returns a tuple with the CertificateProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetCertificateProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CertificateProvider.Get(), o.CertificateProvider.IsSet()
}

// IsSetCertificateProvider returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetCertificateProvider() bool {
	if o != nil && o.CertificateProvider.IsSet() {
		return true
	}

	return false
}

// SetCertificateProvider gets a reference to the given NullableString and assigns it to the CertificateProvider field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetCertificateProvider(v string) {
	o.CertificateProvider.Set(&v)
}

// SetCertificateProviderNil sets the value for CertificateProvider to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetCertificateProviderNil() {
	o.CertificateProvider.Set(nil)
}

// UnsetCertificateProvider ensures that no value is present for CertificateProvider, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetCertificateProvider() {
	o.CertificateProvider.Unset()
}

// GetConfigCmdbDiscovery returns the ConfigCmdbDiscovery field value if set, zero value otherwise.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetConfigCmdbDiscovery() bool {
	if o == nil || IsNil(o.ConfigCmdbDiscovery) {
		var ret bool
		return ret
	}
	return *o.ConfigCmdbDiscovery
}

// GetConfigCmdbDiscoveryOk returns a tuple with the ConfigCmdbDiscovery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetConfigCmdbDiscoveryOk() (*bool, bool) {
	if o == nil || IsNil(o.ConfigCmdbDiscovery) {
		return nil, false
	}
	return o.ConfigCmdbDiscovery, true
}

// IsSetConfigCmdbDiscovery returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetConfigCmdbDiscovery() bool {
	if o != nil && !IsNil(o.ConfigCmdbDiscovery) {
		return true
	}

	return false
}

// SetConfigCmdbDiscovery gets a reference to the given bool and assigns it to the ConfigCmdbDiscovery field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetConfigCmdbDiscovery(v bool) {
	o.ConfigCmdbDiscovery = &v
}

// GetEnableNetworkTypeSelection returns the EnableNetworkTypeSelection field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetEnableNetworkTypeSelection() string {
	if o == nil || IsNil(o.EnableNetworkTypeSelection.Get()) {
		var ret string
		return ret
	}
	return *o.EnableNetworkTypeSelection.Get()
}

// GetEnableNetworkTypeSelectionOk returns a tuple with the EnableNetworkTypeSelection field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetEnableNetworkTypeSelectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnableNetworkTypeSelection.Get(), o.EnableNetworkTypeSelection.IsSet()
}

// IsSetEnableNetworkTypeSelection returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetEnableNetworkTypeSelection() bool {
	if o != nil && o.EnableNetworkTypeSelection.IsSet() {
		return true
	}

	return false
}

// SetEnableNetworkTypeSelection gets a reference to the given NullableString and assigns it to the EnableNetworkTypeSelection field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetEnableNetworkTypeSelection(v string) {
	o.EnableNetworkTypeSelection.Set(&v)
}

// SetEnableNetworkTypeSelectionNil sets the value for EnableNetworkTypeSelection to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetEnableNetworkTypeSelectionNil() {
	o.EnableNetworkTypeSelection.Set(nil)
}

// UnsetEnableNetworkTypeSelection ensures that no value is present for EnableNetworkTypeSelection, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetEnableNetworkTypeSelection() {
	o.EnableNetworkTypeSelection.Unset()
}

// GetKubeUrl returns the KubeUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetKubeUrl() string {
	if o == nil || IsNil(o.KubeUrl.Get()) {
		var ret string
		return ret
	}
	return *o.KubeUrl.Get()
}

// GetKubeUrlOk returns a tuple with the KubeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetKubeUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KubeUrl.Get(), o.KubeUrl.IsSet()
}

// IsSetKubeUrl returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetKubeUrl() bool {
	if o != nil && o.KubeUrl.IsSet() {
		return true
	}

	return false
}

// SetKubeUrl gets a reference to the given NullableString and assigns it to the KubeUrl field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetKubeUrl(v string) {
	o.KubeUrl.Set(&v)
}

// SetKubeUrlNil sets the value for KubeUrl to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetKubeUrlNil() {
	o.KubeUrl.Set(nil)
}

// UnsetKubeUrl ensures that no value is present for KubeUrl, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetKubeUrl() {
	o.KubeUrl.Unset()
}

// GetNetworkServer returns the NetworkServer field value if set, zero value otherwise.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetNetworkServer() AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer {
	if o == nil || IsNil(o.NetworkServer) {
		var ret AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer
		return ret
	}
	return *o.NetworkServer
}

// GetNetworkServerOk returns a tuple with the NetworkServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetNetworkServerOk() (*AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer, bool) {
	if o == nil || IsNil(o.NetworkServer) {
		return nil, false
	}
	return o.NetworkServer, true
}

// IsSetNetworkServer returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetNetworkServer() bool {
	if o != nil && !IsNil(o.NetworkServer) {
		return true
	}

	return false
}

// SetNetworkServer gets a reference to the given AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer and assigns it to the NetworkServer field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetNetworkServer(v AddClouds200ResponseAllOfZoneConfigAnyOfNetworkServer) {
	o.NetworkServer = &v
}

// GetNetworkServerId returns the NetworkServerId field value if set, zero value otherwise.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetNetworkServerId() string {
	if o == nil || IsNil(o.NetworkServerId) {
		var ret string
		return ret
	}
	return *o.NetworkServerId
}

// GetNetworkServerIdOk returns a tuple with the NetworkServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetNetworkServerIdOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkServerId) {
		return nil, false
	}
	return o.NetworkServerId, true
}

// IsSetNetworkServerId returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetNetworkServerId() bool {
	if o != nil && !IsNil(o.NetworkServerId) {
		return true
	}

	return false
}

// SetNetworkServerId gets a reference to the given string and assigns it to the NetworkServerId field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetNetworkServerId(v string) {
	o.NetworkServerId = &v
}

// GetReplicationMode returns the ReplicationMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetReplicationMode() string {
	if o == nil || IsNil(o.ReplicationMode.Get()) {
		var ret string
		return ret
	}
	return *o.ReplicationMode.Get()
}

// GetReplicationModeOk returns a tuple with the ReplicationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetReplicationModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReplicationMode.Get(), o.ReplicationMode.IsSet()
}

// IsSetReplicationMode returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetReplicationMode() bool {
	if o != nil && o.ReplicationMode.IsSet() {
		return true
	}

	return false
}

// SetReplicationMode gets a reference to the given NullableString and assigns it to the ReplicationMode field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetReplicationMode(v string) {
	o.ReplicationMode.Set(&v)
}

// SetReplicationModeNil sets the value for ReplicationMode to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetReplicationModeNil() {
	o.ReplicationMode.Set(nil)
}

// UnsetReplicationMode ensures that no value is present for ReplicationMode, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetReplicationMode() {
	o.ReplicationMode.Unset()
}

// GetSecurityServer returns the SecurityServer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetSecurityServer() string {
	if o == nil || IsNil(o.SecurityServer.Get()) {
		var ret string
		return ret
	}
	return *o.SecurityServer.Get()
}

// GetSecurityServerOk returns a tuple with the SecurityServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) GetSecurityServerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityServer.Get(), o.SecurityServer.IsSet()
}

// IsSetSecurityServer returns a boolean if a field has been set.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) IsSetSecurityServer() bool {
	if o != nil && o.SecurityServer.IsSet() {
		return true
	}

	return false
}

// SetSecurityServer gets a reference to the given NullableString and assigns it to the SecurityServer field.
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetSecurityServer(v string) {
	o.SecurityServer.Set(&v)
}

// SetSecurityServerNil sets the value for SecurityServer to be an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) SetSecurityServerNil() {
	o.SecurityServer.Set(nil)
}

// UnsetSecurityServer ensures that no value is present for SecurityServer, not even an explicit nil
func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnsetSecurityServer() {
	o.SecurityServer.Unset()
}

func (o AddClouds200ResponseAllOfZoneConfigAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddClouds200ResponseAllOfZoneConfigAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApplianceUrl.IsSet() {
		toSerialize["applianceUrl"] = o.ApplianceUrl.Get()
	}
	if o.DatacenterName.IsSet() {
		toSerialize["datacenterName"] = o.DatacenterName.Get()
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if o.InventoryLevel.IsSet() {
		toSerialize["inventoryLevel"] = o.InventoryLevel.Get()
	}
	if o.ConsoleKeymap.IsSet() {
		toSerialize["consoleKeymap"] = o.ConsoleKeymap.Get()
	}
	if o.BackupMode.IsSet() {
		toSerialize["backupMode"] = o.BackupMode.Get()
	}
	if o.CertificateProvider.IsSet() {
		toSerialize["certificateProvider"] = o.CertificateProvider.Get()
	}
	if !IsNil(o.ConfigCmdbDiscovery) {
		toSerialize["configCmdbDiscovery"] = o.ConfigCmdbDiscovery
	}
	if o.EnableNetworkTypeSelection.IsSet() {
		toSerialize["enableNetworkTypeSelection"] = o.EnableNetworkTypeSelection.Get()
	}
	if o.KubeUrl.IsSet() {
		toSerialize["kubeUrl"] = o.KubeUrl.Get()
	}
	if !IsNil(o.NetworkServer) {
		toSerialize["networkServer"] = o.NetworkServer
	}
	if !IsNil(o.NetworkServerId) {
		toSerialize["networkServer.id"] = o.NetworkServerId
	}
	if o.ReplicationMode.IsSet() {
		toSerialize["replicationMode"] = o.ReplicationMode.Get()
	}
	if o.SecurityServer.IsSet() {
		toSerialize["securityServer"] = o.SecurityServer.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddClouds200ResponseAllOfZoneConfigAnyOf struct {
	value *AddClouds200ResponseAllOfZoneConfigAnyOf
	isSet bool
}

func (v NullableAddClouds200ResponseAllOfZoneConfigAnyOf) Get() *AddClouds200ResponseAllOfZoneConfigAnyOf {
	return v.value
}

func (v *NullableAddClouds200ResponseAllOfZoneConfigAnyOf) Set(val *AddClouds200ResponseAllOfZoneConfigAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddClouds200ResponseAllOfZoneConfigAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddClouds200ResponseAllOfZoneConfigAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddClouds200ResponseAllOfZoneConfigAnyOf(val *AddClouds200ResponseAllOfZoneConfigAnyOf) *NullableAddClouds200ResponseAllOfZoneConfigAnyOf {
	return &NullableAddClouds200ResponseAllOfZoneConfigAnyOf{value: val, isSet: true}
}

func (v NullableAddClouds200ResponseAllOfZoneConfigAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddClouds200ResponseAllOfZoneConfigAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddClouds200ResponseAllOfZoneConfigAnyOf) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddClouds200ResponseAllOfZoneConfigAnyOf) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
