/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GenericInstanceConfiguration2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenericInstanceConfiguration2{}

// GenericInstanceConfiguration2 struct for GenericInstanceConfiguration2
type GenericInstanceConfiguration2 struct {
	// User Data. Allows for override of cloud-init based user-data yaml or custom scripts
	UserData             NullableString         `json:"userData,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GenericInstanceConfiguration2 GenericInstanceConfiguration2

// NewGenericInstanceConfiguration2 instantiates a new GenericInstanceConfiguration2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericInstanceConfiguration2() *GenericInstanceConfiguration2 {
	this := GenericInstanceConfiguration2{}
	return &this
}

// NewGenericInstanceConfiguration2WithDefaults instantiates a new GenericInstanceConfiguration2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericInstanceConfiguration2WithDefaults() *GenericInstanceConfiguration2 {
	this := GenericInstanceConfiguration2{}
	return &this
}

// GetUserData returns the UserData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GenericInstanceConfiguration2) GetUserData() string {
	if o == nil || IsNil(o.UserData.Get()) {
		var ret string
		return ret
	}
	return *o.UserData.Get()
}

// GetUserDataOk returns a tuple with the UserData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GenericInstanceConfiguration2) GetUserDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserData.Get(), o.UserData.IsSet()
}

// IsSetUserData returns a boolean if a field has been set.
func (o *GenericInstanceConfiguration2) IsSetUserData() bool {
	if o != nil && o.UserData.IsSet() {
		return true
	}

	return false
}

// SetUserData gets a reference to the given NullableString and assigns it to the UserData field.
func (o *GenericInstanceConfiguration2) SetUserData(v string) {
	o.UserData.Set(&v)
}

// SetUserDataNil sets the value for UserData to be an explicit nil
func (o *GenericInstanceConfiguration2) SetUserDataNil() {
	o.UserData.Set(nil)
}

// UnsetUserData ensures that no value is present for UserData, not even an explicit nil
func (o *GenericInstanceConfiguration2) UnsetUserData() {
	o.UserData.Unset()
}

func (o GenericInstanceConfiguration2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenericInstanceConfiguration2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserData.IsSet() {
		toSerialize["userData"] = o.UserData.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGenericInstanceConfiguration2 struct {
	value *GenericInstanceConfiguration2
	isSet bool
}

func (v NullableGenericInstanceConfiguration2) Get() *GenericInstanceConfiguration2 {
	return v.value
}

func (v *NullableGenericInstanceConfiguration2) Set(val *GenericInstanceConfiguration2) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericInstanceConfiguration2) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericInstanceConfiguration2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericInstanceConfiguration2(val *GenericInstanceConfiguration2) *NullableGenericInstanceConfiguration2 {
	return &NullableGenericInstanceConfiguration2{value: val, isSet: true}
}

func (v NullableGenericInstanceConfiguration2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericInstanceConfiguration2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGenericInstanceConfiguration2) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GenericInstanceConfiguration2) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
