/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstancesNetworkInterfacesNetworkPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstancesNetworkInterfacesNetworkPool{}

// InstancesNetworkInterfacesNetworkPool struct for InstancesNetworkInterfacesNetworkPool
type InstancesNetworkInterfacesNetworkPool struct {
	// id of the ip pool to be used with this network
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _InstancesNetworkInterfacesNetworkPool InstancesNetworkInterfacesNetworkPool

// NewInstancesNetworkInterfacesNetworkPool instantiates a new InstancesNetworkInterfacesNetworkPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesNetworkInterfacesNetworkPool() *InstancesNetworkInterfacesNetworkPool {
	this := InstancesNetworkInterfacesNetworkPool{}
	return &this
}

// NewInstancesNetworkInterfacesNetworkPoolWithDefaults instantiates a new InstancesNetworkInterfacesNetworkPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesNetworkInterfacesNetworkPoolWithDefaults() *InstancesNetworkInterfacesNetworkPool {
	this := InstancesNetworkInterfacesNetworkPool{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstancesNetworkInterfacesNetworkPool) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesNetworkInterfacesNetworkPool) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *InstancesNetworkInterfacesNetworkPool) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InstancesNetworkInterfacesNetworkPool) SetId(v int64) {
	o.Id = &v
}

func (o InstancesNetworkInterfacesNetworkPool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstancesNetworkInterfacesNetworkPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstancesNetworkInterfacesNetworkPool struct {
	value *InstancesNetworkInterfacesNetworkPool
	isSet bool
}

func (v NullableInstancesNetworkInterfacesNetworkPool) Get() *InstancesNetworkInterfacesNetworkPool {
	return v.value
}

func (v *NullableInstancesNetworkInterfacesNetworkPool) Set(val *InstancesNetworkInterfacesNetworkPool) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesNetworkInterfacesNetworkPool) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesNetworkInterfacesNetworkPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesNetworkInterfacesNetworkPool(val *InstancesNetworkInterfacesNetworkPool) *NullableInstancesNetworkInterfacesNetworkPool {
	return &NullableInstancesNetworkInterfacesNetworkPool{value: val, isSet: true}
}

func (v NullableInstancesNetworkInterfacesNetworkPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesNetworkInterfacesNetworkPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstancesNetworkInterfacesNetworkPool) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *InstancesNetworkInterfacesNetworkPool) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
