/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the RemoveClouds200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveClouds200Response{}

// RemoveClouds200Response struct for RemoveClouds200Response
type RemoveClouds200Response struct {
	Success              *bool                  `json:"success,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _RemoveClouds200Response RemoveClouds200Response

// NewRemoveClouds200Response instantiates a new RemoveClouds200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveClouds200Response() *RemoveClouds200Response {
	this := RemoveClouds200Response{}
	return &this
}

// NewRemoveClouds200ResponseWithDefaults instantiates a new RemoveClouds200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveClouds200ResponseWithDefaults() *RemoveClouds200Response {
	this := RemoveClouds200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *RemoveClouds200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveClouds200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// IsSetSuccess returns a boolean if a field has been set.
func (o *RemoveClouds200Response) IsSetSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *RemoveClouds200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o RemoveClouds200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveClouds200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableRemoveClouds200Response struct {
	value *RemoveClouds200Response
	isSet bool
}

func (v NullableRemoveClouds200Response) Get() *RemoveClouds200Response {
	return v.value
}

func (v *NullableRemoveClouds200Response) Set(val *RemoveClouds200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveClouds200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveClouds200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveClouds200Response(val *RemoveClouds200Response) *NullableRemoveClouds200Response {
	return &NullableRemoveClouds200Response{value: val, isSet: true}
}

func (v NullableRemoveClouds200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveClouds200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableRemoveClouds200Response) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *RemoveClouds200Response) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
