/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the MaxContainersPolicyTypeConfiguration4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaxContainersPolicyTypeConfiguration4{}

// MaxContainersPolicyTypeConfiguration4 Configuration settings for the following policy types: - Max Containers
type MaxContainersPolicyTypeConfiguration4 struct {
	MaxContainers        *string                `json:"maxContainers,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _MaxContainersPolicyTypeConfiguration4 MaxContainersPolicyTypeConfiguration4

// NewMaxContainersPolicyTypeConfiguration4 instantiates a new MaxContainersPolicyTypeConfiguration4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaxContainersPolicyTypeConfiguration4() *MaxContainersPolicyTypeConfiguration4 {
	this := MaxContainersPolicyTypeConfiguration4{}
	return &this
}

// NewMaxContainersPolicyTypeConfiguration4WithDefaults instantiates a new MaxContainersPolicyTypeConfiguration4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaxContainersPolicyTypeConfiguration4WithDefaults() *MaxContainersPolicyTypeConfiguration4 {
	this := MaxContainersPolicyTypeConfiguration4{}
	return &this
}

// GetMaxContainers returns the MaxContainers field value if set, zero value otherwise.
func (o *MaxContainersPolicyTypeConfiguration4) GetMaxContainers() string {
	if o == nil || IsNil(o.MaxContainers) {
		var ret string
		return ret
	}
	return *o.MaxContainers
}

// GetMaxContainersOk returns a tuple with the MaxContainers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaxContainersPolicyTypeConfiguration4) GetMaxContainersOk() (*string, bool) {
	if o == nil || IsNil(o.MaxContainers) {
		return nil, false
	}
	return o.MaxContainers, true
}

// IsSetMaxContainers returns a boolean if a field has been set.
func (o *MaxContainersPolicyTypeConfiguration4) IsSetMaxContainers() bool {
	if o != nil && !IsNil(o.MaxContainers) {
		return true
	}

	return false
}

// SetMaxContainers gets a reference to the given string and assigns it to the MaxContainers field.
func (o *MaxContainersPolicyTypeConfiguration4) SetMaxContainers(v string) {
	o.MaxContainers = &v
}

func (o MaxContainersPolicyTypeConfiguration4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaxContainersPolicyTypeConfiguration4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxContainers) {
		toSerialize["maxContainers"] = o.MaxContainers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableMaxContainersPolicyTypeConfiguration4 struct {
	value *MaxContainersPolicyTypeConfiguration4
	isSet bool
}

func (v NullableMaxContainersPolicyTypeConfiguration4) Get() *MaxContainersPolicyTypeConfiguration4 {
	return v.value
}

func (v *NullableMaxContainersPolicyTypeConfiguration4) Set(val *MaxContainersPolicyTypeConfiguration4) {
	v.value = val
	v.isSet = true
}

func (v NullableMaxContainersPolicyTypeConfiguration4) IsSet() bool {
	return v.isSet
}

func (v *NullableMaxContainersPolicyTypeConfiguration4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaxContainersPolicyTypeConfiguration4(val *MaxContainersPolicyTypeConfiguration4) *NullableMaxContainersPolicyTypeConfiguration4 {
	return &NullableMaxContainersPolicyTypeConfiguration4{value: val, isSet: true}
}

func (v NullableMaxContainersPolicyTypeConfiguration4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaxContainersPolicyTypeConfiguration4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableMaxContainersPolicyTypeConfiguration4) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *MaxContainersPolicyTypeConfiguration4) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
