/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstanceContainerServer3ServerOs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceContainerServer3ServerOs{}

// InstanceContainerServer3ServerOs struct for InstanceContainerServer3ServerOs
type InstanceContainerServer3ServerOs struct {
	Id                   *int64                 `json:"id,omitempty"`
	Code                 *string                `json:"code,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Description          NullableString         `json:"description,omitempty"`
	Vendor               *string                `json:"vendor,omitempty"`
	Category             *string                `json:"category,omitempty"`
	OsFamily             *string                `json:"osFamily,omitempty"`
	OsVersion            *string                `json:"osVersion,omitempty"`
	BitCount             *int64                 `json:"bitCount,omitempty"`
	Platform             *string                `json:"platform,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _InstanceContainerServer3ServerOs InstanceContainerServer3ServerOs

// NewInstanceContainerServer3ServerOs instantiates a new InstanceContainerServer3ServerOs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceContainerServer3ServerOs() *InstanceContainerServer3ServerOs {
	this := InstanceContainerServer3ServerOs{}
	return &this
}

// NewInstanceContainerServer3ServerOsWithDefaults instantiates a new InstanceContainerServer3ServerOs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceContainerServer3ServerOsWithDefaults() *InstanceContainerServer3ServerOs {
	this := InstanceContainerServer3ServerOs{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InstanceContainerServer3ServerOs) SetId(v int64) {
	o.Id = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// IsSetCode returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *InstanceContainerServer3ServerOs) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceContainerServer3ServerOs) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceContainerServer3ServerOs) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceContainerServer3ServerOs) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// IsSetDescription returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InstanceContainerServer3ServerOs) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InstanceContainerServer3ServerOs) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InstanceContainerServer3ServerOs) UnsetDescription() {
	o.Description.Unset()
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// IsSetVendor returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *InstanceContainerServer3ServerOs) SetVendor(v string) {
	o.Vendor = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// IsSetCategory returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *InstanceContainerServer3ServerOs) SetCategory(v string) {
	o.Category = &v
}

// GetOsFamily returns the OsFamily field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetOsFamily() string {
	if o == nil || IsNil(o.OsFamily) {
		var ret string
		return ret
	}
	return *o.OsFamily
}

// GetOsFamilyOk returns a tuple with the OsFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetOsFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.OsFamily) {
		return nil, false
	}
	return o.OsFamily, true
}

// IsSetOsFamily returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetOsFamily() bool {
	if o != nil && !IsNil(o.OsFamily) {
		return true
	}

	return false
}

// SetOsFamily gets a reference to the given string and assigns it to the OsFamily field.
func (o *InstanceContainerServer3ServerOs) SetOsFamily(v string) {
	o.OsFamily = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// IsSetOsVersion returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *InstanceContainerServer3ServerOs) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetBitCount returns the BitCount field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetBitCount() int64 {
	if o == nil || IsNil(o.BitCount) {
		var ret int64
		return ret
	}
	return *o.BitCount
}

// GetBitCountOk returns a tuple with the BitCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetBitCountOk() (*int64, bool) {
	if o == nil || IsNil(o.BitCount) {
		return nil, false
	}
	return o.BitCount, true
}

// IsSetBitCount returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetBitCount() bool {
	if o != nil && !IsNil(o.BitCount) {
		return true
	}

	return false
}

// SetBitCount gets a reference to the given int64 and assigns it to the BitCount field.
func (o *InstanceContainerServer3ServerOs) SetBitCount(v int64) {
	o.BitCount = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *InstanceContainerServer3ServerOs) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer3ServerOs) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// IsSetPlatform returns a boolean if a field has been set.
func (o *InstanceContainerServer3ServerOs) IsSetPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *InstanceContainerServer3ServerOs) SetPlatform(v string) {
	o.Platform = &v
}

func (o InstanceContainerServer3ServerOs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceContainerServer3ServerOs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.OsFamily) {
		toSerialize["osFamily"] = o.OsFamily
	}
	if !IsNil(o.OsVersion) {
		toSerialize["osVersion"] = o.OsVersion
	}
	if !IsNil(o.BitCount) {
		toSerialize["bitCount"] = o.BitCount
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstanceContainerServer3ServerOs struct {
	value *InstanceContainerServer3ServerOs
	isSet bool
}

func (v NullableInstanceContainerServer3ServerOs) Get() *InstanceContainerServer3ServerOs {
	return v.value
}

func (v *NullableInstanceContainerServer3ServerOs) Set(val *InstanceContainerServer3ServerOs) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceContainerServer3ServerOs) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceContainerServer3ServerOs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceContainerServer3ServerOs(val *InstanceContainerServer3ServerOs) *NullableInstanceContainerServer3ServerOs {
	return &NullableInstanceContainerServer3ServerOs{value: val, isSet: true}
}

func (v NullableInstanceContainerServer3ServerOs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceContainerServer3ServerOs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstanceContainerServer3ServerOs) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *InstanceContainerServer3ServerOs) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
