/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstanceContainerServer1Plan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceContainerServer1Plan{}

// InstanceContainerServer1Plan struct for InstanceContainerServer1Plan
type InstanceContainerServer1Plan struct {
	Id                   *int64                 `json:"id,omitempty"`
	Code                 *string                `json:"code,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _InstanceContainerServer1Plan InstanceContainerServer1Plan

// NewInstanceContainerServer1Plan instantiates a new InstanceContainerServer1Plan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceContainerServer1Plan() *InstanceContainerServer1Plan {
	this := InstanceContainerServer1Plan{}
	return &this
}

// NewInstanceContainerServer1PlanWithDefaults instantiates a new InstanceContainerServer1Plan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceContainerServer1PlanWithDefaults() *InstanceContainerServer1Plan {
	this := InstanceContainerServer1Plan{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstanceContainerServer1Plan) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer1Plan) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *InstanceContainerServer1Plan) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InstanceContainerServer1Plan) SetId(v int64) {
	o.Id = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InstanceContainerServer1Plan) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer1Plan) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// IsSetCode returns a boolean if a field has been set.
func (o *InstanceContainerServer1Plan) IsSetCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *InstanceContainerServer1Plan) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceContainerServer1Plan) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceContainerServer1Plan) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *InstanceContainerServer1Plan) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceContainerServer1Plan) SetName(v string) {
	o.Name = &v
}

func (o InstanceContainerServer1Plan) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceContainerServer1Plan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstanceContainerServer1Plan struct {
	value *InstanceContainerServer1Plan
	isSet bool
}

func (v NullableInstanceContainerServer1Plan) Get() *InstanceContainerServer1Plan {
	return v.value
}

func (v *NullableInstanceContainerServer1Plan) Set(val *InstanceContainerServer1Plan) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceContainerServer1Plan) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceContainerServer1Plan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceContainerServer1Plan(val *InstanceContainerServer1Plan) *NullableInstanceContainerServer1Plan {
	return &NullableInstanceContainerServer1Plan{value: val, isSet: true}
}

func (v NullableInstanceContainerServer1Plan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceContainerServer1Plan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstanceContainerServer1Plan) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *InstanceContainerServer1Plan) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
