/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BackupTargetsPolicyTypeConfiguration7 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupTargetsPolicyTypeConfiguration7{}

// BackupTargetsPolicyTypeConfiguration7 Configuration settings for the following policy types: - Backup Targets
type BackupTargetsPolicyTypeConfiguration7 struct {
	BackupStorageIds     []int64                `json:"backupStorageIds,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _BackupTargetsPolicyTypeConfiguration7 BackupTargetsPolicyTypeConfiguration7

// NewBackupTargetsPolicyTypeConfiguration7 instantiates a new BackupTargetsPolicyTypeConfiguration7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupTargetsPolicyTypeConfiguration7() *BackupTargetsPolicyTypeConfiguration7 {
	this := BackupTargetsPolicyTypeConfiguration7{}
	return &this
}

// NewBackupTargetsPolicyTypeConfiguration7WithDefaults instantiates a new BackupTargetsPolicyTypeConfiguration7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupTargetsPolicyTypeConfiguration7WithDefaults() *BackupTargetsPolicyTypeConfiguration7 {
	this := BackupTargetsPolicyTypeConfiguration7{}
	return &this
}

// GetBackupStorageIds returns the BackupStorageIds field value if set, zero value otherwise.
func (o *BackupTargetsPolicyTypeConfiguration7) GetBackupStorageIds() []int64 {
	if o == nil || IsNil(o.BackupStorageIds) {
		var ret []int64
		return ret
	}
	return o.BackupStorageIds
}

// GetBackupStorageIdsOk returns a tuple with the BackupStorageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackupTargetsPolicyTypeConfiguration7) GetBackupStorageIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.BackupStorageIds) {
		return nil, false
	}
	return o.BackupStorageIds, true
}

// IsSetBackupStorageIds returns a boolean if a field has been set.
func (o *BackupTargetsPolicyTypeConfiguration7) IsSetBackupStorageIds() bool {
	if o != nil && !IsNil(o.BackupStorageIds) {
		return true
	}

	return false
}

// SetBackupStorageIds gets a reference to the given []int64 and assigns it to the BackupStorageIds field.
func (o *BackupTargetsPolicyTypeConfiguration7) SetBackupStorageIds(v []int64) {
	o.BackupStorageIds = v
}

func (o BackupTargetsPolicyTypeConfiguration7) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupTargetsPolicyTypeConfiguration7) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupStorageIds) {
		toSerialize["backupStorageIds"] = o.BackupStorageIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableBackupTargetsPolicyTypeConfiguration7 struct {
	value *BackupTargetsPolicyTypeConfiguration7
	isSet bool
}

func (v NullableBackupTargetsPolicyTypeConfiguration7) Get() *BackupTargetsPolicyTypeConfiguration7 {
	return v.value
}

func (v *NullableBackupTargetsPolicyTypeConfiguration7) Set(val *BackupTargetsPolicyTypeConfiguration7) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupTargetsPolicyTypeConfiguration7) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupTargetsPolicyTypeConfiguration7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupTargetsPolicyTypeConfiguration7(val *BackupTargetsPolicyTypeConfiguration7) *NullableBackupTargetsPolicyTypeConfiguration7 {
	return &NullableBackupTargetsPolicyTypeConfiguration7{value: val, isSet: true}
}

func (v NullableBackupTargetsPolicyTypeConfiguration7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupTargetsPolicyTypeConfiguration7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableBackupTargetsPolicyTypeConfiguration7) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *BackupTargetsPolicyTypeConfiguration7) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
