/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ClusterServersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterServersInner{}

// ClusterServersInner struct for ClusterServersInner
type ClusterServersInner struct {
	Id                   *int64                                `json:"id,omitempty"`
	Name                 *string                               `json:"name,omitempty"`
	TypeSet              *ClusterServersInnerTypeSet           `json:"typeSet,omitempty"`
	ComputeServerType    *ClusterServersInnerComputeServerType `json:"computeServerType,omitempty"`
	AdditionalProperties map[string]interface{}                `json:",remain"`
}

type _ClusterServersInner ClusterServersInner

// NewClusterServersInner instantiates a new ClusterServersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterServersInner() *ClusterServersInner {
	this := ClusterServersInner{}
	return &this
}

// NewClusterServersInnerWithDefaults instantiates a new ClusterServersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterServersInnerWithDefaults() *ClusterServersInner {
	this := ClusterServersInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClusterServersInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterServersInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *ClusterServersInner) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ClusterServersInner) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterServersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterServersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *ClusterServersInner) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterServersInner) SetName(v string) {
	o.Name = &v
}

// GetTypeSet returns the TypeSet field value if set, zero value otherwise.
func (o *ClusterServersInner) GetTypeSet() ClusterServersInnerTypeSet {
	if o == nil || IsNil(o.TypeSet) {
		var ret ClusterServersInnerTypeSet
		return ret
	}
	return *o.TypeSet
}

// GetTypeSetOk returns a tuple with the TypeSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterServersInner) GetTypeSetOk() (*ClusterServersInnerTypeSet, bool) {
	if o == nil || IsNil(o.TypeSet) {
		return nil, false
	}
	return o.TypeSet, true
}

// IsSetTypeSet returns a boolean if a field has been set.
func (o *ClusterServersInner) IsSetTypeSet() bool {
	if o != nil && !IsNil(o.TypeSet) {
		return true
	}

	return false
}

// SetTypeSet gets a reference to the given ClusterServersInnerTypeSet and assigns it to the TypeSet field.
func (o *ClusterServersInner) SetTypeSet(v ClusterServersInnerTypeSet) {
	o.TypeSet = &v
}

// GetComputeServerType returns the ComputeServerType field value if set, zero value otherwise.
func (o *ClusterServersInner) GetComputeServerType() ClusterServersInnerComputeServerType {
	if o == nil || IsNil(o.ComputeServerType) {
		var ret ClusterServersInnerComputeServerType
		return ret
	}
	return *o.ComputeServerType
}

// GetComputeServerTypeOk returns a tuple with the ComputeServerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterServersInner) GetComputeServerTypeOk() (*ClusterServersInnerComputeServerType, bool) {
	if o == nil || IsNil(o.ComputeServerType) {
		return nil, false
	}
	return o.ComputeServerType, true
}

// IsSetComputeServerType returns a boolean if a field has been set.
func (o *ClusterServersInner) IsSetComputeServerType() bool {
	if o != nil && !IsNil(o.ComputeServerType) {
		return true
	}

	return false
}

// SetComputeServerType gets a reference to the given ClusterServersInnerComputeServerType and assigns it to the ComputeServerType field.
func (o *ClusterServersInner) SetComputeServerType(v ClusterServersInnerComputeServerType) {
	o.ComputeServerType = &v
}

func (o ClusterServersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterServersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TypeSet) {
		toSerialize["typeSet"] = o.TypeSet
	}
	if !IsNil(o.ComputeServerType) {
		toSerialize["computeServerType"] = o.ComputeServerType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableClusterServersInner struct {
	value *ClusterServersInner
	isSet bool
}

func (v NullableClusterServersInner) Get() *ClusterServersInner {
	return v.value
}

func (v *NullableClusterServersInner) Set(val *ClusterServersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterServersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterServersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterServersInner(val *ClusterServersInner) *NullableClusterServersInner {
	return &NullableClusterServersInner{value: val, isSet: true}
}

func (v NullableClusterServersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterServersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableClusterServersInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ClusterServersInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
