/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the RequiredNetworkPolicyTypeConfiguration3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequiredNetworkPolicyTypeConfiguration3{}

// RequiredNetworkPolicyTypeConfiguration3 - Instance Networks
type RequiredNetworkPolicyTypeConfiguration3 struct {
	RequiredNetworks     []int64                `json:"requiredNetworks"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _RequiredNetworkPolicyTypeConfiguration3 RequiredNetworkPolicyTypeConfiguration3

// NewRequiredNetworkPolicyTypeConfiguration3 instantiates a new RequiredNetworkPolicyTypeConfiguration3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequiredNetworkPolicyTypeConfiguration3(requiredNetworks []int64) *RequiredNetworkPolicyTypeConfiguration3 {
	this := RequiredNetworkPolicyTypeConfiguration3{}
	this.RequiredNetworks = requiredNetworks
	return &this
}

// NewRequiredNetworkPolicyTypeConfiguration3WithDefaults instantiates a new RequiredNetworkPolicyTypeConfiguration3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequiredNetworkPolicyTypeConfiguration3WithDefaults() *RequiredNetworkPolicyTypeConfiguration3 {
	this := RequiredNetworkPolicyTypeConfiguration3{}
	return &this
}

// GetRequiredNetworks returns the RequiredNetworks field value
func (o *RequiredNetworkPolicyTypeConfiguration3) GetRequiredNetworks() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.RequiredNetworks
}

// GetRequiredNetworksOk returns a tuple with the RequiredNetworks field value
// and a boolean to check if the value has been set.
func (o *RequiredNetworkPolicyTypeConfiguration3) GetRequiredNetworksOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredNetworks, true
}

// SetRequiredNetworks sets field value
func (o *RequiredNetworkPolicyTypeConfiguration3) SetRequiredNetworks(v []int64) {
	o.RequiredNetworks = v
}

func (o RequiredNetworkPolicyTypeConfiguration3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequiredNetworkPolicyTypeConfiguration3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requiredNetworks"] = o.RequiredNetworks

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableRequiredNetworkPolicyTypeConfiguration3 struct {
	value *RequiredNetworkPolicyTypeConfiguration3
	isSet bool
}

func (v NullableRequiredNetworkPolicyTypeConfiguration3) Get() *RequiredNetworkPolicyTypeConfiguration3 {
	return v.value
}

func (v *NullableRequiredNetworkPolicyTypeConfiguration3) Set(val *RequiredNetworkPolicyTypeConfiguration3) {
	v.value = val
	v.isSet = true
}

func (v NullableRequiredNetworkPolicyTypeConfiguration3) IsSet() bool {
	return v.isSet
}

func (v *NullableRequiredNetworkPolicyTypeConfiguration3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequiredNetworkPolicyTypeConfiguration3(val *RequiredNetworkPolicyTypeConfiguration3) *NullableRequiredNetworkPolicyTypeConfiguration3 {
	return &NullableRequiredNetworkPolicyTypeConfiguration3{value: val, isSet: true}
}

func (v NullableRequiredNetworkPolicyTypeConfiguration3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequiredNetworkPolicyTypeConfiguration3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableRequiredNetworkPolicyTypeConfiguration3) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *RequiredNetworkPolicyTypeConfiguration3) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
