/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AmazonInstanceConfiguration1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmazonInstanceConfiguration1{}

// AmazonInstanceConfiguration1 struct for AmazonInstanceConfiguration1
type AmazonInstanceConfiguration1 struct {
	// Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.
	NoAgent NullableBool `json:"noAgent,omitempty"`
	// Amazon Cloud Type
	IsEC2 *string `json:"isEC2,omitempty"`
	// Amazon Zone
	AvailabilityId *string `json:"availabilityId,omitempty"`
	// Security Group
	SecurityId *string `json:"securityId,omitempty"`
	// Public IP
	PublicIpType *string `json:"publicIpType,omitempty"`
	// IAM Profile
	InstanceProfile *string `json:"instanceProfile,omitempty"`
	// KMS Key ID
	KmsKeyId             *string                `json:"kmsKeyId,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AmazonInstanceConfiguration1 AmazonInstanceConfiguration1

// NewAmazonInstanceConfiguration1 instantiates a new AmazonInstanceConfiguration1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonInstanceConfiguration1() *AmazonInstanceConfiguration1 {
	this := AmazonInstanceConfiguration1{}
	var noAgent bool = false
	this.NoAgent = *NewNullableBool(&noAgent)
	var isEC2 string = "false"
	this.IsEC2 = &isEC2
	return &this
}

// NewAmazonInstanceConfiguration1WithDefaults instantiates a new AmazonInstanceConfiguration1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonInstanceConfiguration1WithDefaults() *AmazonInstanceConfiguration1 {
	this := AmazonInstanceConfiguration1{}
	var noAgent bool = false
	this.NoAgent = *NewNullableBool(&noAgent)
	var isEC2 string = "false"
	this.IsEC2 = &isEC2
	return &this
}

// GetNoAgent returns the NoAgent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AmazonInstanceConfiguration1) GetNoAgent() bool {
	if o == nil || IsNil(o.NoAgent.Get()) {
		var ret bool
		return ret
	}
	return *o.NoAgent.Get()
}

// GetNoAgentOk returns a tuple with the NoAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AmazonInstanceConfiguration1) GetNoAgentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.NoAgent.Get(), o.NoAgent.IsSet()
}

// IsSetNoAgent returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetNoAgent() bool {
	if o != nil && o.NoAgent.IsSet() {
		return true
	}

	return false
}

// SetNoAgent gets a reference to the given NullableBool and assigns it to the NoAgent field.
func (o *AmazonInstanceConfiguration1) SetNoAgent(v bool) {
	o.NoAgent.Set(&v)
}

// SetNoAgentNil sets the value for NoAgent to be an explicit nil
func (o *AmazonInstanceConfiguration1) SetNoAgentNil() {
	o.NoAgent.Set(nil)
}

// UnsetNoAgent ensures that no value is present for NoAgent, not even an explicit nil
func (o *AmazonInstanceConfiguration1) UnsetNoAgent() {
	o.NoAgent.Unset()
}

// GetIsEC2 returns the IsEC2 field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetIsEC2() string {
	if o == nil || IsNil(o.IsEC2) {
		var ret string
		return ret
	}
	return *o.IsEC2
}

// GetIsEC2Ok returns a tuple with the IsEC2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetIsEC2Ok() (*string, bool) {
	if o == nil || IsNil(o.IsEC2) {
		return nil, false
	}
	return o.IsEC2, true
}

// IsSetIsEC2 returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetIsEC2() bool {
	if o != nil && !IsNil(o.IsEC2) {
		return true
	}

	return false
}

// SetIsEC2 gets a reference to the given string and assigns it to the IsEC2 field.
func (o *AmazonInstanceConfiguration1) SetIsEC2(v string) {
	o.IsEC2 = &v
}

// GetAvailabilityId returns the AvailabilityId field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetAvailabilityId() string {
	if o == nil || IsNil(o.AvailabilityId) {
		var ret string
		return ret
	}
	return *o.AvailabilityId
}

// GetAvailabilityIdOk returns a tuple with the AvailabilityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetAvailabilityIdOk() (*string, bool) {
	if o == nil || IsNil(o.AvailabilityId) {
		return nil, false
	}
	return o.AvailabilityId, true
}

// IsSetAvailabilityId returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetAvailabilityId() bool {
	if o != nil && !IsNil(o.AvailabilityId) {
		return true
	}

	return false
}

// SetAvailabilityId gets a reference to the given string and assigns it to the AvailabilityId field.
func (o *AmazonInstanceConfiguration1) SetAvailabilityId(v string) {
	o.AvailabilityId = &v
}

// GetSecurityId returns the SecurityId field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetSecurityId() string {
	if o == nil || IsNil(o.SecurityId) {
		var ret string
		return ret
	}
	return *o.SecurityId
}

// GetSecurityIdOk returns a tuple with the SecurityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetSecurityIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityId) {
		return nil, false
	}
	return o.SecurityId, true
}

// IsSetSecurityId returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetSecurityId() bool {
	if o != nil && !IsNil(o.SecurityId) {
		return true
	}

	return false
}

// SetSecurityId gets a reference to the given string and assigns it to the SecurityId field.
func (o *AmazonInstanceConfiguration1) SetSecurityId(v string) {
	o.SecurityId = &v
}

// GetPublicIpType returns the PublicIpType field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetPublicIpType() string {
	if o == nil || IsNil(o.PublicIpType) {
		var ret string
		return ret
	}
	return *o.PublicIpType
}

// GetPublicIpTypeOk returns a tuple with the PublicIpType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetPublicIpTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PublicIpType) {
		return nil, false
	}
	return o.PublicIpType, true
}

// IsSetPublicIpType returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetPublicIpType() bool {
	if o != nil && !IsNil(o.PublicIpType) {
		return true
	}

	return false
}

// SetPublicIpType gets a reference to the given string and assigns it to the PublicIpType field.
func (o *AmazonInstanceConfiguration1) SetPublicIpType(v string) {
	o.PublicIpType = &v
}

// GetInstanceProfile returns the InstanceProfile field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetInstanceProfile() string {
	if o == nil || IsNil(o.InstanceProfile) {
		var ret string
		return ret
	}
	return *o.InstanceProfile
}

// GetInstanceProfileOk returns a tuple with the InstanceProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetInstanceProfileOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceProfile) {
		return nil, false
	}
	return o.InstanceProfile, true
}

// IsSetInstanceProfile returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetInstanceProfile() bool {
	if o != nil && !IsNil(o.InstanceProfile) {
		return true
	}

	return false
}

// SetInstanceProfile gets a reference to the given string and assigns it to the InstanceProfile field.
func (o *AmazonInstanceConfiguration1) SetInstanceProfile(v string) {
	o.InstanceProfile = &v
}

// GetKmsKeyId returns the KmsKeyId field value if set, zero value otherwise.
func (o *AmazonInstanceConfiguration1) GetKmsKeyId() string {
	if o == nil || IsNil(o.KmsKeyId) {
		var ret string
		return ret
	}
	return *o.KmsKeyId
}

// GetKmsKeyIdOk returns a tuple with the KmsKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonInstanceConfiguration1) GetKmsKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KmsKeyId) {
		return nil, false
	}
	return o.KmsKeyId, true
}

// IsSetKmsKeyId returns a boolean if a field has been set.
func (o *AmazonInstanceConfiguration1) IsSetKmsKeyId() bool {
	if o != nil && !IsNil(o.KmsKeyId) {
		return true
	}

	return false
}

// SetKmsKeyId gets a reference to the given string and assigns it to the KmsKeyId field.
func (o *AmazonInstanceConfiguration1) SetKmsKeyId(v string) {
	o.KmsKeyId = &v
}

func (o AmazonInstanceConfiguration1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AmazonInstanceConfiguration1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NoAgent.IsSet() {
		toSerialize["noAgent"] = o.NoAgent.Get()
	}
	if !IsNil(o.IsEC2) {
		toSerialize["isEC2"] = o.IsEC2
	}
	if !IsNil(o.AvailabilityId) {
		toSerialize["availabilityId"] = o.AvailabilityId
	}
	if !IsNil(o.SecurityId) {
		toSerialize["securityId"] = o.SecurityId
	}
	if !IsNil(o.PublicIpType) {
		toSerialize["publicIpType"] = o.PublicIpType
	}
	if !IsNil(o.InstanceProfile) {
		toSerialize["instanceProfile"] = o.InstanceProfile
	}
	if !IsNil(o.KmsKeyId) {
		toSerialize["kmsKeyId"] = o.KmsKeyId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAmazonInstanceConfiguration1 struct {
	value *AmazonInstanceConfiguration1
	isSet bool
}

func (v NullableAmazonInstanceConfiguration1) Get() *AmazonInstanceConfiguration1 {
	return v.value
}

func (v *NullableAmazonInstanceConfiguration1) Set(val *AmazonInstanceConfiguration1) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonInstanceConfiguration1) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonInstanceConfiguration1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonInstanceConfiguration1(val *AmazonInstanceConfiguration1) *NullableAmazonInstanceConfiguration1 {
	return &NullableAmazonInstanceConfiguration1{value: val, isSet: true}
}

func (v NullableAmazonInstanceConfiguration1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonInstanceConfiguration1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAmazonInstanceConfiguration1) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AmazonInstanceConfiguration1) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
