/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner{}

// InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner struct for InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner
type InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner struct {
	Id                     *int64                                                                                    `json:"id,omitempty"`
	Code                   *string                                                                                   `json:"code,omitempty"`
	Name                   *string                                                                                   `json:"name,omitempty"`
	Description            NullableString                                                                            `json:"description,omitempty"`
	Category               NullableString                                                                            `json:"category,omitempty"`
	ExternalType           NullableString                                                                            `json:"externalType,omitempty"`
	Creatable              *bool                                                                                     `json:"creatable,omitempty"`
	Overlay                *bool                                                                                     `json:"overlay,omitempty"`
	NameEditable           *bool                                                                                     `json:"nameEditable,omitempty"`
	CidrRequired           *bool                                                                                     `json:"cidrRequired,omitempty"`
	CidrEditable           *bool                                                                                     `json:"cidrEditable,omitempty"`
	DhcpServerEditable     *bool                                                                                     `json:"dhcpServerEditable,omitempty"`
	DnsEditable            *bool                                                                                     `json:"dnsEditable,omitempty"`
	GatewayEditable        *bool                                                                                     `json:"gatewayEditable,omitempty"`
	VlanIdEditable         *bool                                                                                     `json:"vlanIdEditable,omitempty"`
	StaticOverrideEditable *bool                                                                                     `json:"staticOverrideEditable,omitempty"`
	NetworkDomainEditable  *bool                                                                                     `json:"networkDomainEditable,omitempty"`
	CanAssignPool          *bool                                                                                     `json:"canAssignPool,omitempty"`
	Deletable              *bool                                                                                     `json:"deletable,omitempty"`
	HasNetworkServer       *bool                                                                                     `json:"hasNetworkServer,omitempty"`
	HasCidr                *bool                                                                                     `json:"hasCidr,omitempty"`
	HasStaticRoutes        *bool                                                                                     `json:"hasStaticRoutes,omitempty"`
	HasFloatingIps         *bool                                                                                     `json:"hasFloatingIps,omitempty"`
	OptionTypes            []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner      `json:"optionTypes,omitempty"`
	RouteOptionTypes       []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner `json:"routeOptionTypes,omitempty"`
	AdditionalProperties   map[string]interface{}                                                                    `json:",remain"`
}

type _InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner

// NewInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner instantiates a new InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner() *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner {
	this := InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner{}
	return &this
}

// NewInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerWithDefaults instantiates a new InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerWithDefaults() *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner {
	this := InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetId(v int64) {
	o.Id = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// IsSetCode returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// IsSetDescription returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnsetDescription() {
	o.Description.Unset()
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// IsSetCategory returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCategory(v string) {
	o.Category.Set(&v)
}

// SetCategoryNil sets the value for Category to be an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnsetCategory() {
	o.Category.Unset()
}

// GetExternalType returns the ExternalType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetExternalType() string {
	if o == nil || IsNil(o.ExternalType.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalType.Get()
}

// GetExternalTypeOk returns a tuple with the ExternalType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetExternalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalType.Get(), o.ExternalType.IsSet()
}

// IsSetExternalType returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetExternalType() bool {
	if o != nil && o.ExternalType.IsSet() {
		return true
	}

	return false
}

// SetExternalType gets a reference to the given NullableString and assigns it to the ExternalType field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetExternalType(v string) {
	o.ExternalType.Set(&v)
}

// SetExternalTypeNil sets the value for ExternalType to be an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetExternalTypeNil() {
	o.ExternalType.Set(nil)
}

// UnsetExternalType ensures that no value is present for ExternalType, not even an explicit nil
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnsetExternalType() {
	o.ExternalType.Unset()
}

// GetCreatable returns the Creatable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCreatable() bool {
	if o == nil || IsNil(o.Creatable) {
		var ret bool
		return ret
	}
	return *o.Creatable
}

// GetCreatableOk returns a tuple with the Creatable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCreatableOk() (*bool, bool) {
	if o == nil || IsNil(o.Creatable) {
		return nil, false
	}
	return o.Creatable, true
}

// IsSetCreatable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCreatable() bool {
	if o != nil && !IsNil(o.Creatable) {
		return true
	}

	return false
}

// SetCreatable gets a reference to the given bool and assigns it to the Creatable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCreatable(v bool) {
	o.Creatable = &v
}

// GetOverlay returns the Overlay field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetOverlay() bool {
	if o == nil || IsNil(o.Overlay) {
		var ret bool
		return ret
	}
	return *o.Overlay
}

// GetOverlayOk returns a tuple with the Overlay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetOverlayOk() (*bool, bool) {
	if o == nil || IsNil(o.Overlay) {
		return nil, false
	}
	return o.Overlay, true
}

// IsSetOverlay returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetOverlay() bool {
	if o != nil && !IsNil(o.Overlay) {
		return true
	}

	return false
}

// SetOverlay gets a reference to the given bool and assigns it to the Overlay field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetOverlay(v bool) {
	o.Overlay = &v
}

// GetNameEditable returns the NameEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetNameEditable() bool {
	if o == nil || IsNil(o.NameEditable) {
		var ret bool
		return ret
	}
	return *o.NameEditable
}

// GetNameEditableOk returns a tuple with the NameEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetNameEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.NameEditable) {
		return nil, false
	}
	return o.NameEditable, true
}

// IsSetNameEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetNameEditable() bool {
	if o != nil && !IsNil(o.NameEditable) {
		return true
	}

	return false
}

// SetNameEditable gets a reference to the given bool and assigns it to the NameEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetNameEditable(v bool) {
	o.NameEditable = &v
}

// GetCidrRequired returns the CidrRequired field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCidrRequired() bool {
	if o == nil || IsNil(o.CidrRequired) {
		var ret bool
		return ret
	}
	return *o.CidrRequired
}

// GetCidrRequiredOk returns a tuple with the CidrRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCidrRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.CidrRequired) {
		return nil, false
	}
	return o.CidrRequired, true
}

// IsSetCidrRequired returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCidrRequired() bool {
	if o != nil && !IsNil(o.CidrRequired) {
		return true
	}

	return false
}

// SetCidrRequired gets a reference to the given bool and assigns it to the CidrRequired field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCidrRequired(v bool) {
	o.CidrRequired = &v
}

// GetCidrEditable returns the CidrEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCidrEditable() bool {
	if o == nil || IsNil(o.CidrEditable) {
		var ret bool
		return ret
	}
	return *o.CidrEditable
}

// GetCidrEditableOk returns a tuple with the CidrEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCidrEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.CidrEditable) {
		return nil, false
	}
	return o.CidrEditable, true
}

// IsSetCidrEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCidrEditable() bool {
	if o != nil && !IsNil(o.CidrEditable) {
		return true
	}

	return false
}

// SetCidrEditable gets a reference to the given bool and assigns it to the CidrEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCidrEditable(v bool) {
	o.CidrEditable = &v
}

// GetDhcpServerEditable returns the DhcpServerEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDhcpServerEditable() bool {
	if o == nil || IsNil(o.DhcpServerEditable) {
		var ret bool
		return ret
	}
	return *o.DhcpServerEditable
}

// GetDhcpServerEditableOk returns a tuple with the DhcpServerEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDhcpServerEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.DhcpServerEditable) {
		return nil, false
	}
	return o.DhcpServerEditable, true
}

// IsSetDhcpServerEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetDhcpServerEditable() bool {
	if o != nil && !IsNil(o.DhcpServerEditable) {
		return true
	}

	return false
}

// SetDhcpServerEditable gets a reference to the given bool and assigns it to the DhcpServerEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetDhcpServerEditable(v bool) {
	o.DhcpServerEditable = &v
}

// GetDnsEditable returns the DnsEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDnsEditable() bool {
	if o == nil || IsNil(o.DnsEditable) {
		var ret bool
		return ret
	}
	return *o.DnsEditable
}

// GetDnsEditableOk returns a tuple with the DnsEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDnsEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.DnsEditable) {
		return nil, false
	}
	return o.DnsEditable, true
}

// IsSetDnsEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetDnsEditable() bool {
	if o != nil && !IsNil(o.DnsEditable) {
		return true
	}

	return false
}

// SetDnsEditable gets a reference to the given bool and assigns it to the DnsEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetDnsEditable(v bool) {
	o.DnsEditable = &v
}

// GetGatewayEditable returns the GatewayEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetGatewayEditable() bool {
	if o == nil || IsNil(o.GatewayEditable) {
		var ret bool
		return ret
	}
	return *o.GatewayEditable
}

// GetGatewayEditableOk returns a tuple with the GatewayEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetGatewayEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.GatewayEditable) {
		return nil, false
	}
	return o.GatewayEditable, true
}

// IsSetGatewayEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetGatewayEditable() bool {
	if o != nil && !IsNil(o.GatewayEditable) {
		return true
	}

	return false
}

// SetGatewayEditable gets a reference to the given bool and assigns it to the GatewayEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetGatewayEditable(v bool) {
	o.GatewayEditable = &v
}

// GetVlanIdEditable returns the VlanIdEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetVlanIdEditable() bool {
	if o == nil || IsNil(o.VlanIdEditable) {
		var ret bool
		return ret
	}
	return *o.VlanIdEditable
}

// GetVlanIdEditableOk returns a tuple with the VlanIdEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetVlanIdEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.VlanIdEditable) {
		return nil, false
	}
	return o.VlanIdEditable, true
}

// IsSetVlanIdEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetVlanIdEditable() bool {
	if o != nil && !IsNil(o.VlanIdEditable) {
		return true
	}

	return false
}

// SetVlanIdEditable gets a reference to the given bool and assigns it to the VlanIdEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetVlanIdEditable(v bool) {
	o.VlanIdEditable = &v
}

// GetStaticOverrideEditable returns the StaticOverrideEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetStaticOverrideEditable() bool {
	if o == nil || IsNil(o.StaticOverrideEditable) {
		var ret bool
		return ret
	}
	return *o.StaticOverrideEditable
}

// GetStaticOverrideEditableOk returns a tuple with the StaticOverrideEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetStaticOverrideEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.StaticOverrideEditable) {
		return nil, false
	}
	return o.StaticOverrideEditable, true
}

// IsSetStaticOverrideEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetStaticOverrideEditable() bool {
	if o != nil && !IsNil(o.StaticOverrideEditable) {
		return true
	}

	return false
}

// SetStaticOverrideEditable gets a reference to the given bool and assigns it to the StaticOverrideEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetStaticOverrideEditable(v bool) {
	o.StaticOverrideEditable = &v
}

// GetNetworkDomainEditable returns the NetworkDomainEditable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetNetworkDomainEditable() bool {
	if o == nil || IsNil(o.NetworkDomainEditable) {
		var ret bool
		return ret
	}
	return *o.NetworkDomainEditable
}

// GetNetworkDomainEditableOk returns a tuple with the NetworkDomainEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetNetworkDomainEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.NetworkDomainEditable) {
		return nil, false
	}
	return o.NetworkDomainEditable, true
}

// IsSetNetworkDomainEditable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetNetworkDomainEditable() bool {
	if o != nil && !IsNil(o.NetworkDomainEditable) {
		return true
	}

	return false
}

// SetNetworkDomainEditable gets a reference to the given bool and assigns it to the NetworkDomainEditable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetNetworkDomainEditable(v bool) {
	o.NetworkDomainEditable = &v
}

// GetCanAssignPool returns the CanAssignPool field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCanAssignPool() bool {
	if o == nil || IsNil(o.CanAssignPool) {
		var ret bool
		return ret
	}
	return *o.CanAssignPool
}

// GetCanAssignPoolOk returns a tuple with the CanAssignPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetCanAssignPoolOk() (*bool, bool) {
	if o == nil || IsNil(o.CanAssignPool) {
		return nil, false
	}
	return o.CanAssignPool, true
}

// IsSetCanAssignPool returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetCanAssignPool() bool {
	if o != nil && !IsNil(o.CanAssignPool) {
		return true
	}

	return false
}

// SetCanAssignPool gets a reference to the given bool and assigns it to the CanAssignPool field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetCanAssignPool(v bool) {
	o.CanAssignPool = &v
}

// GetDeletable returns the Deletable field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDeletable() bool {
	if o == nil || IsNil(o.Deletable) {
		var ret bool
		return ret
	}
	return *o.Deletable
}

// GetDeletableOk returns a tuple with the Deletable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetDeletableOk() (*bool, bool) {
	if o == nil || IsNil(o.Deletable) {
		return nil, false
	}
	return o.Deletable, true
}

// IsSetDeletable returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetDeletable() bool {
	if o != nil && !IsNil(o.Deletable) {
		return true
	}

	return false
}

// SetDeletable gets a reference to the given bool and assigns it to the Deletable field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetDeletable(v bool) {
	o.Deletable = &v
}

// GetHasNetworkServer returns the HasNetworkServer field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasNetworkServer() bool {
	if o == nil || IsNil(o.HasNetworkServer) {
		var ret bool
		return ret
	}
	return *o.HasNetworkServer
}

// GetHasNetworkServerOk returns a tuple with the HasNetworkServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasNetworkServerOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNetworkServer) {
		return nil, false
	}
	return o.HasNetworkServer, true
}

// IsSetHasNetworkServer returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetHasNetworkServer() bool {
	if o != nil && !IsNil(o.HasNetworkServer) {
		return true
	}

	return false
}

// SetHasNetworkServer gets a reference to the given bool and assigns it to the HasNetworkServer field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetHasNetworkServer(v bool) {
	o.HasNetworkServer = &v
}

// GetHasCidr returns the HasCidr field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasCidr() bool {
	if o == nil || IsNil(o.HasCidr) {
		var ret bool
		return ret
	}
	return *o.HasCidr
}

// GetHasCidrOk returns a tuple with the HasCidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasCidrOk() (*bool, bool) {
	if o == nil || IsNil(o.HasCidr) {
		return nil, false
	}
	return o.HasCidr, true
}

// IsSetHasCidr returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetHasCidr() bool {
	if o != nil && !IsNil(o.HasCidr) {
		return true
	}

	return false
}

// SetHasCidr gets a reference to the given bool and assigns it to the HasCidr field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetHasCidr(v bool) {
	o.HasCidr = &v
}

// GetHasStaticRoutes returns the HasStaticRoutes field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasStaticRoutes() bool {
	if o == nil || IsNil(o.HasStaticRoutes) {
		var ret bool
		return ret
	}
	return *o.HasStaticRoutes
}

// GetHasStaticRoutesOk returns a tuple with the HasStaticRoutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasStaticRoutesOk() (*bool, bool) {
	if o == nil || IsNil(o.HasStaticRoutes) {
		return nil, false
	}
	return o.HasStaticRoutes, true
}

// IsSetHasStaticRoutes returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetHasStaticRoutes() bool {
	if o != nil && !IsNil(o.HasStaticRoutes) {
		return true
	}

	return false
}

// SetHasStaticRoutes gets a reference to the given bool and assigns it to the HasStaticRoutes field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetHasStaticRoutes(v bool) {
	o.HasStaticRoutes = &v
}

// GetHasFloatingIps returns the HasFloatingIps field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasFloatingIps() bool {
	if o == nil || IsNil(o.HasFloatingIps) {
		var ret bool
		return ret
	}
	return *o.HasFloatingIps
}

// GetHasFloatingIpsOk returns a tuple with the HasFloatingIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetHasFloatingIpsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasFloatingIps) {
		return nil, false
	}
	return o.HasFloatingIps, true
}

// IsSetHasFloatingIps returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetHasFloatingIps() bool {
	if o != nil && !IsNil(o.HasFloatingIps) {
		return true
	}

	return false
}

// SetHasFloatingIps gets a reference to the given bool and assigns it to the HasFloatingIps field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetHasFloatingIps(v bool) {
	o.HasFloatingIps = &v
}

// GetOptionTypes returns the OptionTypes field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetOptionTypes() []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner {
	if o == nil || IsNil(o.OptionTypes) {
		var ret []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner
		return ret
	}
	return o.OptionTypes
}

// GetOptionTypesOk returns a tuple with the OptionTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetOptionTypesOk() ([]InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner, bool) {
	if o == nil || IsNil(o.OptionTypes) {
		return nil, false
	}
	return o.OptionTypes, true
}

// IsSetOptionTypes returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetOptionTypes() bool {
	if o != nil && !IsNil(o.OptionTypes) {
		return true
	}

	return false
}

// SetOptionTypes gets a reference to the given []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner and assigns it to the OptionTypes field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetOptionTypes(v []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerOptionTypesInner) {
	o.OptionTypes = v
}

// GetRouteOptionTypes returns the RouteOptionTypes field value if set, zero value otherwise.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetRouteOptionTypes() []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner {
	if o == nil || IsNil(o.RouteOptionTypes) {
		var ret []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner
		return ret
	}
	return o.RouteOptionTypes
}

// GetRouteOptionTypesOk returns a tuple with the RouteOptionTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) GetRouteOptionTypesOk() ([]InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner, bool) {
	if o == nil || IsNil(o.RouteOptionTypes) {
		return nil, false
	}
	return o.RouteOptionTypes, true
}

// IsSetRouteOptionTypes returns a boolean if a field has been set.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSetRouteOptionTypes() bool {
	if o != nil && !IsNil(o.RouteOptionTypes) {
		return true
	}

	return false
}

// SetRouteOptionTypes gets a reference to the given []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner and assigns it to the RouteOptionTypes field.
func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) SetRouteOptionTypes(v []InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInnerRouteOptionTypesInner) {
	o.RouteOptionTypes = v
}

func (o InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if o.ExternalType.IsSet() {
		toSerialize["externalType"] = o.ExternalType.Get()
	}
	if !IsNil(o.Creatable) {
		toSerialize["creatable"] = o.Creatable
	}
	if !IsNil(o.Overlay) {
		toSerialize["overlay"] = o.Overlay
	}
	if !IsNil(o.NameEditable) {
		toSerialize["nameEditable"] = o.NameEditable
	}
	if !IsNil(o.CidrRequired) {
		toSerialize["cidrRequired"] = o.CidrRequired
	}
	if !IsNil(o.CidrEditable) {
		toSerialize["cidrEditable"] = o.CidrEditable
	}
	if !IsNil(o.DhcpServerEditable) {
		toSerialize["dhcpServerEditable"] = o.DhcpServerEditable
	}
	if !IsNil(o.DnsEditable) {
		toSerialize["dnsEditable"] = o.DnsEditable
	}
	if !IsNil(o.GatewayEditable) {
		toSerialize["gatewayEditable"] = o.GatewayEditable
	}
	if !IsNil(o.VlanIdEditable) {
		toSerialize["vlanIdEditable"] = o.VlanIdEditable
	}
	if !IsNil(o.StaticOverrideEditable) {
		toSerialize["staticOverrideEditable"] = o.StaticOverrideEditable
	}
	if !IsNil(o.NetworkDomainEditable) {
		toSerialize["networkDomainEditable"] = o.NetworkDomainEditable
	}
	if !IsNil(o.CanAssignPool) {
		toSerialize["canAssignPool"] = o.CanAssignPool
	}
	if !IsNil(o.Deletable) {
		toSerialize["deletable"] = o.Deletable
	}
	if !IsNil(o.HasNetworkServer) {
		toSerialize["hasNetworkServer"] = o.HasNetworkServer
	}
	if !IsNil(o.HasCidr) {
		toSerialize["hasCidr"] = o.HasCidr
	}
	if !IsNil(o.HasStaticRoutes) {
		toSerialize["hasStaticRoutes"] = o.HasStaticRoutes
	}
	if !IsNil(o.HasFloatingIps) {
		toSerialize["hasFloatingIps"] = o.HasFloatingIps
	}
	if !IsNil(o.OptionTypes) {
		toSerialize["optionTypes"] = o.OptionTypes
	}
	if !IsNil(o.RouteOptionTypes) {
		toSerialize["routeOptionTypes"] = o.RouteOptionTypes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner struct {
	value *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner
	isSet bool
}

func (v NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) Get() *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner {
	return v.value
}

func (v *NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) Set(val *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner(val *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) *NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner {
	return &NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner{value: val, isSet: true}
}

func (v NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *InstanceTypeInstanceTypeLayoutsInnerProvisionTypeNetworkTypesInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
