/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddBaremetalHost200ResponseServerAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddBaremetalHost200ResponseServerAccount{}

// AddBaremetalHost200ResponseServerAccount struct for AddBaremetalHost200ResponseServerAccount
type AddBaremetalHost200ResponseServerAccount struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddBaremetalHost200ResponseServerAccount AddBaremetalHost200ResponseServerAccount

// NewAddBaremetalHost200ResponseServerAccount instantiates a new AddBaremetalHost200ResponseServerAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddBaremetalHost200ResponseServerAccount() *AddBaremetalHost200ResponseServerAccount {
	this := AddBaremetalHost200ResponseServerAccount{}
	return &this
}

// NewAddBaremetalHost200ResponseServerAccountWithDefaults instantiates a new AddBaremetalHost200ResponseServerAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddBaremetalHost200ResponseServerAccountWithDefaults() *AddBaremetalHost200ResponseServerAccount {
	this := AddBaremetalHost200ResponseServerAccount{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AddBaremetalHost200ResponseServerAccount) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBaremetalHost200ResponseServerAccount) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *AddBaremetalHost200ResponseServerAccount) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *AddBaremetalHost200ResponseServerAccount) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddBaremetalHost200ResponseServerAccount) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBaremetalHost200ResponseServerAccount) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *AddBaremetalHost200ResponseServerAccount) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddBaremetalHost200ResponseServerAccount) SetName(v string) {
	o.Name = &v
}

func (o AddBaremetalHost200ResponseServerAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddBaremetalHost200ResponseServerAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddBaremetalHost200ResponseServerAccount struct {
	value *AddBaremetalHost200ResponseServerAccount
	isSet bool
}

func (v NullableAddBaremetalHost200ResponseServerAccount) Get() *AddBaremetalHost200ResponseServerAccount {
	return v.value
}

func (v *NullableAddBaremetalHost200ResponseServerAccount) Set(val *AddBaremetalHost200ResponseServerAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableAddBaremetalHost200ResponseServerAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAddBaremetalHost200ResponseServerAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddBaremetalHost200ResponseServerAccount(val *AddBaremetalHost200ResponseServerAccount) *NullableAddBaremetalHost200ResponseServerAccount {
	return &NullableAddBaremetalHost200ResponseServerAccount{value: val, isSet: true}
}

func (v NullableAddBaremetalHost200ResponseServerAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddBaremetalHost200ResponseServerAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddBaremetalHost200ResponseServerAccount) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddBaremetalHost200ResponseServerAccount) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
