/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.7
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner{}

// AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner struct for AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner
type AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner struct {
	Ip                   *string `json:"ip,omitempty"`
	Port                 *int32  `json:"port,omitempty"`
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner

// NewAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner instantiates a new AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner() *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner {
	this := AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner{}
	return &this
}

// NewAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInnerWithDefaults instantiates a new AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInnerWithDefaults() *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner {
	this := AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// IsSetIp returns a boolean if a field has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) IsSetIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) SetIp(v string) {
	o.Ip = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// IsSetPort returns a boolean if a field has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) IsSetPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) SetPort(v int32) {
	o.Port = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) SetName(v string) {
	o.Name = &v
}

func (o AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) UnmarshalJSON(data []byte) (err error) {
	varAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner := _AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner{}

	err = json.Unmarshal(data, &varAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner)

	if err != nil {
		return err
	}

	*o = AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner(varAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		delete(additionalProperties, "port")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner struct {
	value *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner
	isSet bool
}

func (v NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) Get() *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner {
	return v.value
}

func (v *NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) Set(val *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner(val *AddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) *NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner {
	return &NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner{value: val, isSet: true}
}

func (v NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddInstance200ResponseAllOfOneOfInstanceConnectionInfoInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
