/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AddIntegrationsRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddIntegrationsRequestOneOf{}

// AddIntegrationsRequestOneOf struct for AddIntegrationsRequestOneOf
type AddIntegrationsRequestOneOf struct {
	Integration          AddIntegrationsRequestOneOfIntegration `json:"integration"`
	AdditionalProperties map[string]interface{}
}

type _AddIntegrationsRequestOneOf AddIntegrationsRequestOneOf

// NewAddIntegrationsRequestOneOf instantiates a new AddIntegrationsRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddIntegrationsRequestOneOf(integration AddIntegrationsRequestOneOfIntegration) *AddIntegrationsRequestOneOf {
	this := AddIntegrationsRequestOneOf{}
	this.Integration = integration
	return &this
}

// NewAddIntegrationsRequestOneOfWithDefaults instantiates a new AddIntegrationsRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddIntegrationsRequestOneOfWithDefaults() *AddIntegrationsRequestOneOf {
	this := AddIntegrationsRequestOneOf{}
	return &this
}

// GetIntegration returns the Integration field value
func (o *AddIntegrationsRequestOneOf) GetIntegration() AddIntegrationsRequestOneOfIntegration {
	if o == nil {
		var ret AddIntegrationsRequestOneOfIntegration
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *AddIntegrationsRequestOneOf) GetIntegrationOk() (*AddIntegrationsRequestOneOfIntegration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *AddIntegrationsRequestOneOf) SetIntegration(v AddIntegrationsRequestOneOfIntegration) {
	o.Integration = v
}

func (o AddIntegrationsRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddIntegrationsRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integration"] = o.Integration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *AddIntegrationsRequestOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddIntegrationsRequestOneOf := _AddIntegrationsRequestOneOf{}

	err = json.Unmarshal(data, &varAddIntegrationsRequestOneOf)

	if err != nil {
		return err
	}

	*o = AddIntegrationsRequestOneOf(varAddIntegrationsRequestOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "integration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddIntegrationsRequestOneOf struct {
	value *AddIntegrationsRequestOneOf
	isSet bool
}

func (v NullableAddIntegrationsRequestOneOf) Get() *AddIntegrationsRequestOneOf {
	return v.value
}

func (v *NullableAddIntegrationsRequestOneOf) Set(val *AddIntegrationsRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddIntegrationsRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddIntegrationsRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddIntegrationsRequestOneOf(val *AddIntegrationsRequestOneOf) *NullableAddIntegrationsRequestOneOf {
	return &NullableAddIntegrationsRequestOneOf{value: val, isSet: true}
}

func (v NullableAddIntegrationsRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddIntegrationsRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
