/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SetInstanceSecurityGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetInstanceSecurityGroups200Response{}

// SetInstanceSecurityGroups200Response struct for SetInstanceSecurityGroups200Response
type SetInstanceSecurityGroups200Response struct {
	// Array of security group objects
	SecurityGroups       []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner `json:"securityGroups,omitempty"`
	Success              *bool                                                           `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SetInstanceSecurityGroups200Response SetInstanceSecurityGroups200Response

// NewSetInstanceSecurityGroups200Response instantiates a new SetInstanceSecurityGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetInstanceSecurityGroups200Response() *SetInstanceSecurityGroups200Response {
	this := SetInstanceSecurityGroups200Response{}
	return &this
}

// NewSetInstanceSecurityGroups200ResponseWithDefaults instantiates a new SetInstanceSecurityGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetInstanceSecurityGroups200ResponseWithDefaults() *SetInstanceSecurityGroups200Response {
	this := SetInstanceSecurityGroups200Response{}
	return &this
}

// GetSecurityGroups returns the SecurityGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SetInstanceSecurityGroups200Response) GetSecurityGroups() []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner {
	if o == nil {
		var ret []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner
		return ret
	}
	return o.SecurityGroups
}

// GetSecurityGroupsOk returns a tuple with the SecurityGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SetInstanceSecurityGroups200Response) GetSecurityGroupsOk() ([]ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner, bool) {
	if o == nil || IsNil(o.SecurityGroups) {
		return nil, false
	}
	return o.SecurityGroups, true
}

// IsSetSecurityGroups returns a boolean if a field has been set.
func (o *SetInstanceSecurityGroups200Response) IsSetSecurityGroups() bool {
	if o != nil && !IsNil(o.SecurityGroups) {
		return true
	}

	return false
}

// SetSecurityGroups gets a reference to the given []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner and assigns it to the SecurityGroups field.
func (o *SetInstanceSecurityGroups200Response) SetSecurityGroups(v []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner) {
	o.SecurityGroups = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *SetInstanceSecurityGroups200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetInstanceSecurityGroups200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// IsSetSuccess returns a boolean if a field has been set.
func (o *SetInstanceSecurityGroups200Response) IsSetSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *SetInstanceSecurityGroups200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o SetInstanceSecurityGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetInstanceSecurityGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SecurityGroups != nil {
		toSerialize["securityGroups"] = o.SecurityGroups
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *SetInstanceSecurityGroups200Response) UnmarshalJSON(data []byte) (err error) {
	varSetInstanceSecurityGroups200Response := _SetInstanceSecurityGroups200Response{}

	err = json.Unmarshal(data, &varSetInstanceSecurityGroups200Response)

	if err != nil {
		return err
	}

	*o = SetInstanceSecurityGroups200Response(varSetInstanceSecurityGroups200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "securityGroups")
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetInstanceSecurityGroups200Response struct {
	value *SetInstanceSecurityGroups200Response
	isSet bool
}

func (v NullableSetInstanceSecurityGroups200Response) Get() *SetInstanceSecurityGroups200Response {
	return v.value
}

func (v *NullableSetInstanceSecurityGroups200Response) Set(val *SetInstanceSecurityGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSetInstanceSecurityGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSetInstanceSecurityGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetInstanceSecurityGroups200Response(val *SetInstanceSecurityGroups200Response) *NullableSetInstanceSecurityGroups200Response {
	return &NullableSetInstanceSecurityGroups200Response{value: val, isSet: true}
}

func (v NullableSetInstanceSecurityGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetInstanceSecurityGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
