/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateEnvironmentsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvironmentsRequest{}

// UpdateEnvironmentsRequest struct for UpdateEnvironmentsRequest
type UpdateEnvironmentsRequest struct {
	Environment          UpdateEnvironmentsRequestEnvironment `json:"environment"`
	AdditionalProperties map[string]interface{}
}

type _UpdateEnvironmentsRequest UpdateEnvironmentsRequest

// NewUpdateEnvironmentsRequest instantiates a new UpdateEnvironmentsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvironmentsRequest(environment UpdateEnvironmentsRequestEnvironment) *UpdateEnvironmentsRequest {
	this := UpdateEnvironmentsRequest{}
	this.Environment = environment
	return &this
}

// NewUpdateEnvironmentsRequestWithDefaults instantiates a new UpdateEnvironmentsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvironmentsRequestWithDefaults() *UpdateEnvironmentsRequest {
	this := UpdateEnvironmentsRequest{}
	return &this
}

// GetEnvironment returns the Environment field value
func (o *UpdateEnvironmentsRequest) GetEnvironment() UpdateEnvironmentsRequestEnvironment {
	if o == nil {
		var ret UpdateEnvironmentsRequestEnvironment
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvironmentsRequest) GetEnvironmentOk() (*UpdateEnvironmentsRequestEnvironment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *UpdateEnvironmentsRequest) SetEnvironment(v UpdateEnvironmentsRequestEnvironment) {
	o.Environment = v
}

func (o UpdateEnvironmentsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvironmentsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environment"] = o.Environment

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *UpdateEnvironmentsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateEnvironmentsRequest := _UpdateEnvironmentsRequest{}

	err = json.Unmarshal(data, &varUpdateEnvironmentsRequest)

	if err != nil {
		return err
	}

	*o = UpdateEnvironmentsRequest(varUpdateEnvironmentsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateEnvironmentsRequest struct {
	value *UpdateEnvironmentsRequest
	isSet bool
}

func (v NullableUpdateEnvironmentsRequest) Get() *UpdateEnvironmentsRequest {
	return v.value
}

func (v *NullableUpdateEnvironmentsRequest) Set(val *UpdateEnvironmentsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvironmentsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvironmentsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvironmentsRequest(val *UpdateEnvironmentsRequest) *NullableUpdateEnvironmentsRequest {
	return &NullableUpdateEnvironmentsRequest{value: val, isSet: true}
}

func (v NullableUpdateEnvironmentsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvironmentsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
