/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// AddVDIPoolsRequestVdiPoolOneOfConfigPlan - struct for AddVDIPoolsRequestVdiPoolOneOfConfigPlan
type AddVDIPoolsRequestVdiPoolOneOfConfigPlan struct {
	Int64  *int64
	String *string
}

// int64AsAddVDIPoolsRequestVdiPoolOneOfConfigPlan is a convenience function that returns int64 wrapped in AddVDIPoolsRequestVdiPoolOneOfConfigPlan
func Int64AsAddVDIPoolsRequestVdiPoolOneOfConfigPlan(v *int64) AddVDIPoolsRequestVdiPoolOneOfConfigPlan {
	return AddVDIPoolsRequestVdiPoolOneOfConfigPlan{
		Int64: v,
	}
}

// stringAsAddVDIPoolsRequestVdiPoolOneOfConfigPlan is a convenience function that returns string wrapped in AddVDIPoolsRequestVdiPoolOneOfConfigPlan
func StringAsAddVDIPoolsRequestVdiPoolOneOfConfigPlan(v *string) AddVDIPoolsRequestVdiPoolOneOfConfigPlan {
	return AddVDIPoolsRequestVdiPoolOneOfConfigPlan{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *AddVDIPoolsRequestVdiPoolOneOfConfigPlan) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int64
	err = newStrictDecoder(data).Decode(&dst.Int64)
	if err == nil {
		jsonInt64, _ := json.Marshal(dst.Int64)
		if string(jsonInt64) == "{}" { // empty struct
			dst.Int64 = nil
		} else {
			if err = validator.Validate(dst.Int64); err != nil {
				dst.Int64 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int64 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int64 = nil
		dst.String = nil

		return NewResponseValidationError("data matches more than one schema in oneOf(AddVDIPoolsRequestVdiPoolOneOfConfigPlan)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return NewResponseValidationError("data failed to match schemas in oneOf(AddVDIPoolsRequestVdiPoolOneOfConfigPlan)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AddVDIPoolsRequestVdiPoolOneOfConfigPlan) MarshalJSON() ([]byte, error) {
	if src.Int64 != nil {
		return json.Marshal(&src.Int64)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AddVDIPoolsRequestVdiPoolOneOfConfigPlan) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Int64 != nil {
		return obj.Int64
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AddVDIPoolsRequestVdiPoolOneOfConfigPlan) GetActualInstanceValue() interface{} {
	if obj.Int64 != nil {
		return *obj.Int64
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan struct {
	value *AddVDIPoolsRequestVdiPoolOneOfConfigPlan
	isSet bool
}

func (v NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) Get() *AddVDIPoolsRequestVdiPoolOneOfConfigPlan {
	return v.value
}

func (v *NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) Set(val *AddVDIPoolsRequestVdiPoolOneOfConfigPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan(val *AddVDIPoolsRequestVdiPoolOneOfConfigPlan) *NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan {
	return &NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan{value: val, isSet: true}
}

func (v NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddVDIPoolsRequestVdiPoolOneOfConfigPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
