/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddVdiAllocation200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddVdiAllocation200Response{}

// AddVdiAllocation200Response struct for AddVdiAllocation200Response
type AddVdiAllocation200Response struct {
	Desktop              *ListVdi200ResponseAllOfDesktopsInner `json:"desktop,omitempty"`
	Success              *bool                                 `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddVdiAllocation200Response AddVdiAllocation200Response

// NewAddVdiAllocation200Response instantiates a new AddVdiAllocation200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddVdiAllocation200Response() *AddVdiAllocation200Response {
	this := AddVdiAllocation200Response{}
	return &this
}

// NewAddVdiAllocation200ResponseWithDefaults instantiates a new AddVdiAllocation200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddVdiAllocation200ResponseWithDefaults() *AddVdiAllocation200Response {
	this := AddVdiAllocation200Response{}
	return &this
}

// GetDesktop returns the Desktop field value if set, zero value otherwise.
func (o *AddVdiAllocation200Response) GetDesktop() ListVdi200ResponseAllOfDesktopsInner {
	if o == nil || IsNil(o.Desktop) {
		var ret ListVdi200ResponseAllOfDesktopsInner
		return ret
	}
	return *o.Desktop
}

// GetDesktopOk returns a tuple with the Desktop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddVdiAllocation200Response) GetDesktopOk() (*ListVdi200ResponseAllOfDesktopsInner, bool) {
	if o == nil || IsNil(o.Desktop) {
		return nil, false
	}
	return o.Desktop, true
}

// IsSetDesktop returns a boolean if a field has been set.
func (o *AddVdiAllocation200Response) IsSetDesktop() bool {
	if o != nil && !IsNil(o.Desktop) {
		return true
	}

	return false
}

// SetDesktop gets a reference to the given ListVdi200ResponseAllOfDesktopsInner and assigns it to the Desktop field.
func (o *AddVdiAllocation200Response) SetDesktop(v ListVdi200ResponseAllOfDesktopsInner) {
	o.Desktop = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *AddVdiAllocation200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddVdiAllocation200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// IsSetSuccess returns a boolean if a field has been set.
func (o *AddVdiAllocation200Response) IsSetSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *AddVdiAllocation200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o AddVdiAllocation200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddVdiAllocation200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Desktop) {
		toSerialize["desktop"] = o.Desktop
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *AddVdiAllocation200Response) UnmarshalJSON(data []byte) (err error) {
	varAddVdiAllocation200Response := _AddVdiAllocation200Response{}

	err = json.Unmarshal(data, &varAddVdiAllocation200Response)

	if err != nil {
		return err
	}

	*o = AddVdiAllocation200Response(varAddVdiAllocation200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "desktop")
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddVdiAllocation200Response struct {
	value *AddVdiAllocation200Response
	isSet bool
}

func (v NullableAddVdiAllocation200Response) Get() *AddVdiAllocation200Response {
	return v.value
}

func (v *NullableAddVdiAllocation200Response) Set(val *AddVdiAllocation200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVdiAllocation200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVdiAllocation200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVdiAllocation200Response(val *AddVdiAllocation200Response) *NullableAddVdiAllocation200Response {
	return &NullableAddVdiAllocation200Response{value: val, isSet: true}
}

func (v NullableAddVdiAllocation200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddVdiAllocation200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
