/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.7
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdatePriceSetsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePriceSetsRequest{}

// UpdatePriceSetsRequest struct for UpdatePriceSetsRequest
type UpdatePriceSetsRequest struct {
	PriceSet             UpdatePriceSetsRequestPriceSet `json:"priceSet"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePriceSetsRequest UpdatePriceSetsRequest

// NewUpdatePriceSetsRequest instantiates a new UpdatePriceSetsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePriceSetsRequest(priceSet UpdatePriceSetsRequestPriceSet) *UpdatePriceSetsRequest {
	this := UpdatePriceSetsRequest{}
	this.PriceSet = priceSet
	return &this
}

// NewUpdatePriceSetsRequestWithDefaults instantiates a new UpdatePriceSetsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePriceSetsRequestWithDefaults() *UpdatePriceSetsRequest {
	this := UpdatePriceSetsRequest{}
	return &this
}

// GetPriceSet returns the PriceSet field value
func (o *UpdatePriceSetsRequest) GetPriceSet() UpdatePriceSetsRequestPriceSet {
	if o == nil {
		var ret UpdatePriceSetsRequestPriceSet
		return ret
	}

	return o.PriceSet
}

// GetPriceSetOk returns a tuple with the PriceSet field value
// and a boolean to check if the value has been set.
func (o *UpdatePriceSetsRequest) GetPriceSetOk() (*UpdatePriceSetsRequestPriceSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceSet, true
}

// SetPriceSet sets field value
func (o *UpdatePriceSetsRequest) SetPriceSet(v UpdatePriceSetsRequestPriceSet) {
	o.PriceSet = v
}

func (o UpdatePriceSetsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePriceSetsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["priceSet"] = o.PriceSet

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *UpdatePriceSetsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"priceSet",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePriceSetsRequest := _UpdatePriceSetsRequest{}

	err = json.Unmarshal(data, &varUpdatePriceSetsRequest)

	if err != nil {
		return err
	}

	*o = UpdatePriceSetsRequest(varUpdatePriceSetsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "priceSet")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePriceSetsRequest struct {
	value *UpdatePriceSetsRequest
	isSet bool
}

func (v NullableUpdatePriceSetsRequest) Get() *UpdatePriceSetsRequest {
	return v.value
}

func (v *NullableUpdatePriceSetsRequest) Set(val *UpdatePriceSetsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePriceSetsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePriceSetsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePriceSetsRequest(val *UpdatePriceSetsRequest) *NullableUpdatePriceSetsRequest {
	return &NullableUpdatePriceSetsRequest{value: val, isSet: true}
}

func (v NullableUpdatePriceSetsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePriceSetsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
