/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the CreateNetworkGroupRequestNetworkGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNetworkGroupRequestNetworkGroup{}

// CreateNetworkGroupRequestNetworkGroup struct for CreateNetworkGroupRequestNetworkGroup
type CreateNetworkGroupRequestNetworkGroup struct {
	Name                 *string                  `json:"name,omitempty"`
	Description          *string                  `json:"description,omitempty"`
	Networks             []int64                  `json:"networks,omitempty"`
	Subnets              []map[string]interface{} `json:"subnets,omitempty"`
	AdditionalProperties map[string]interface{}   `json:",remain"`
}

type _CreateNetworkGroupRequestNetworkGroup CreateNetworkGroupRequestNetworkGroup

// NewCreateNetworkGroupRequestNetworkGroup instantiates a new CreateNetworkGroupRequestNetworkGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNetworkGroupRequestNetworkGroup() *CreateNetworkGroupRequestNetworkGroup {
	this := CreateNetworkGroupRequestNetworkGroup{}
	return &this
}

// NewCreateNetworkGroupRequestNetworkGroupWithDefaults instantiates a new CreateNetworkGroupRequestNetworkGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNetworkGroupRequestNetworkGroupWithDefaults() *CreateNetworkGroupRequestNetworkGroup {
	this := CreateNetworkGroupRequestNetworkGroup{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateNetworkGroupRequestNetworkGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateNetworkGroupRequestNetworkGroup) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateNetworkGroupRequestNetworkGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// IsSetDescription returns a boolean if a field has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) IsSetDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateNetworkGroupRequestNetworkGroup) SetDescription(v string) {
	o.Description = &v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *CreateNetworkGroupRequestNetworkGroup) GetNetworks() []int64 {
	if o == nil || IsNil(o.Networks) {
		var ret []int64
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) GetNetworksOk() ([]int64, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// IsSetNetworks returns a boolean if a field has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) IsSetNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []int64 and assigns it to the Networks field.
func (o *CreateNetworkGroupRequestNetworkGroup) SetNetworks(v []int64) {
	o.Networks = v
}

// GetSubnets returns the Subnets field value if set, zero value otherwise.
func (o *CreateNetworkGroupRequestNetworkGroup) GetSubnets() []map[string]interface{} {
	if o == nil || IsNil(o.Subnets) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) GetSubnetsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Subnets) {
		return nil, false
	}
	return o.Subnets, true
}

// IsSetSubnets returns a boolean if a field has been set.
func (o *CreateNetworkGroupRequestNetworkGroup) IsSetSubnets() bool {
	if o != nil && !IsNil(o.Subnets) {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given []map[string]interface{} and assigns it to the Subnets field.
func (o *CreateNetworkGroupRequestNetworkGroup) SetSubnets(v []map[string]interface{}) {
	o.Subnets = v
}

func (o CreateNetworkGroupRequestNetworkGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNetworkGroupRequestNetworkGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.Subnets) {
		toSerialize["subnets"] = o.Subnets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableCreateNetworkGroupRequestNetworkGroup struct {
	value *CreateNetworkGroupRequestNetworkGroup
	isSet bool
}

func (v NullableCreateNetworkGroupRequestNetworkGroup) Get() *CreateNetworkGroupRequestNetworkGroup {
	return v.value
}

func (v *NullableCreateNetworkGroupRequestNetworkGroup) Set(val *CreateNetworkGroupRequestNetworkGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNetworkGroupRequestNetworkGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNetworkGroupRequestNetworkGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNetworkGroupRequestNetworkGroup(val *CreateNetworkGroupRequestNetworkGroup) *NullableCreateNetworkGroupRequestNetworkGroup {
	return &NullableCreateNetworkGroupRequestNetworkGroup{value: val, isSet: true}
}

func (v NullableCreateNetworkGroupRequestNetworkGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNetworkGroupRequestNetworkGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (o *CreateNetworkGroupRequestNetworkGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
