/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.7
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AddRolesRequestRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddRolesRequestRole{}

// AddRolesRequestRole Payload for creating a new role
type AddRolesRequestRole struct {
	// Authority (Name)
	Authority string `json:"authority"`
	// Description
	Description NullableString `json:"description,omitempty"`
	// An optional override for the default landing page after login for a user.
	LandingUrl NullableString `json:"landingUrl,omitempty"`
	// Role type
	RoleType *string `json:"roleType,omitempty"`
	// Base Role ID. Create the new role with the same permissions and access levels that the specified base role has. If this is not passed, the role is create without any permissions.
	BaseRoleId *int64 `json:"baseRoleId,omitempty"`
	// Multitenant roles are copied to all tenant accounts and kept in sync until a sub-tenant user modifies their copy of the role. *Only available to master tenant*
	Multitenant *bool `json:"multitenant,omitempty"`
	// Multitenant Locked, prevents sub-tenant users from modifying their copy of multienant roles. *Only available to master tenant*
	MultitenantLocked *bool          `json:"multitenantLocked,omitempty"`
	DefaultPersona    NullableString `json:"defaultPersona,omitempty"`
	// Set the access level for the specified permissions.
	FeaturePermissions []AddRolesRequestRoleFeaturePermissionsInner `json:"featurePermissions,omitempty"`
	// Set the default access level for for groups (sites). Only applies to user roles.
	GlobalSiteAccess *string `json:"globalSiteAccess,omitempty"`
	// Set the access level for the specified groups (sites). Only applies to user roles.
	Sites []AddRolesRequestRoleSitesInner `json:"sites,omitempty"`
	// Set the default access level for for clouds (zones). Only applies to base account (tenant) roles.
	GlobalZoneAccess *string `json:"globalZoneAccess,omitempty"`
	// Set the access level for the specified clouds (zones). Only applies to base account (tenant) roles.
	Zones []AddRolesRequestRoleZonesInner `json:"zones,omitempty"`
	// Set the default access level for for instance types
	GlobalInstanceTypeAccess *string `json:"globalInstanceTypeAccess,omitempty"`
	// Set the access level for the specified instance types
	InstanceTypePermissions []AddRolesRequestRoleInstanceTypePermissionsInner `json:"instanceTypePermissions,omitempty"`
	// Set the default access level for blueprints
	GlobalAppTemplateAccess *string `json:"globalAppTemplateAccess,omitempty"`
	// Set the access level for the specified blueprints (appTemplates)
	AppTemplatePermissions []AddRolesRequestRoleAppTemplatePermissionsInner `json:"appTemplatePermissions,omitempty"`
	// Set the default access level for catalog item types
	GlobalCatalogItemTypeAccess *string `json:"globalCatalogItemTypeAccess,omitempty"`
	// Set the access level for the specified catalog item types
	CatalogItemTypePermissions []AddRolesRequestRoleCatalogItemTypePermissionsInner `json:"catalogItemTypePermissions,omitempty"`
	// Set the default access level for personas
	GlobalPersonaAccess *string `json:"globalPersonaAccess,omitempty"`
	// Set the access level for the specified personas
	PersonaPermissions []AddRolesRequestRolePersonaPermissionsInner `json:"personaPermissions,omitempty"`
	// Set the default access level for VDI pools
	GlobalVdiPoolAccess *string `json:"globalVdiPoolAccess,omitempty"`
	// Set the access level for the specified VDI pools
	VdiPoolPermissions []AddRolesRequestRoleVdiPoolPermissionsInner `json:"vdiPoolPermissions,omitempty"`
	// Set the default access level for report types
	GlobalReportTypeAccess *string `json:"globalReportTypeAccess,omitempty"`
	// Set the access level for the specified report types
	ReportTypePermissions []AddRolesRequestRoleReportTypePermissionsInner `json:"reportTypePermissions,omitempty"`
	// Set the default access level for tasks
	GlobalTaskAccess *string `json:"globalTaskAccess,omitempty"`
	// Set the access level for the specified tasks
	TaskPermissions []AddRolesRequestRoleTaskPermissionsInner `json:"taskPermissions,omitempty"`
	// Set the default access level for workflows (taskSets)
	GlobalTaskSetAccess *string `json:"globalTaskSetAccess,omitempty"`
	// Set the access level for the specified workflows (taskSets)
	TaskSetPermissions []AddRolesRequestRoleTaskSetPermissionsInner `json:"taskSetPermissions,omitempty"`
	// Set the role owner (tenant) by ID. *Only available to master tenant*
	Owner                *int64 `json:"owner,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddRolesRequestRole AddRolesRequestRole

// NewAddRolesRequestRole instantiates a new AddRolesRequestRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddRolesRequestRole(authority string) *AddRolesRequestRole {
	this := AddRolesRequestRole{}
	this.Authority = authority
	var roleType string = "user"
	this.RoleType = &roleType
	var multitenant bool = false
	this.Multitenant = &multitenant
	var multitenantLocked bool = false
	this.MultitenantLocked = &multitenantLocked
	return &this
}

// NewAddRolesRequestRoleWithDefaults instantiates a new AddRolesRequestRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddRolesRequestRoleWithDefaults() *AddRolesRequestRole {
	this := AddRolesRequestRole{}
	var roleType string = "user"
	this.RoleType = &roleType
	var multitenant bool = false
	this.Multitenant = &multitenant
	var multitenantLocked bool = false
	this.MultitenantLocked = &multitenantLocked
	return &this
}

// GetAuthority returns the Authority field value
func (o *AddRolesRequestRole) GetAuthority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authority, true
}

// SetAuthority sets field value
func (o *AddRolesRequestRole) SetAuthority(v string) {
	o.Authority = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddRolesRequestRole) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddRolesRequestRole) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// IsSetDescription returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *AddRolesRequestRole) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *AddRolesRequestRole) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *AddRolesRequestRole) UnsetDescription() {
	o.Description.Unset()
}

// GetLandingUrl returns the LandingUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddRolesRequestRole) GetLandingUrl() string {
	if o == nil || IsNil(o.LandingUrl.Get()) {
		var ret string
		return ret
	}
	return *o.LandingUrl.Get()
}

// GetLandingUrlOk returns a tuple with the LandingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddRolesRequestRole) GetLandingUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LandingUrl.Get(), o.LandingUrl.IsSet()
}

// IsSetLandingUrl returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetLandingUrl() bool {
	if o != nil && o.LandingUrl.IsSet() {
		return true
	}

	return false
}

// SetLandingUrl gets a reference to the given NullableString and assigns it to the LandingUrl field.
func (o *AddRolesRequestRole) SetLandingUrl(v string) {
	o.LandingUrl.Set(&v)
}

// SetLandingUrlNil sets the value for LandingUrl to be an explicit nil
func (o *AddRolesRequestRole) SetLandingUrlNil() {
	o.LandingUrl.Set(nil)
}

// UnsetLandingUrl ensures that no value is present for LandingUrl, not even an explicit nil
func (o *AddRolesRequestRole) UnsetLandingUrl() {
	o.LandingUrl.Unset()
}

// GetRoleType returns the RoleType field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetRoleType() string {
	if o == nil || IsNil(o.RoleType) {
		var ret string
		return ret
	}
	return *o.RoleType
}

// GetRoleTypeOk returns a tuple with the RoleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetRoleTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RoleType) {
		return nil, false
	}
	return o.RoleType, true
}

// IsSetRoleType returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetRoleType() bool {
	if o != nil && !IsNil(o.RoleType) {
		return true
	}

	return false
}

// SetRoleType gets a reference to the given string and assigns it to the RoleType field.
func (o *AddRolesRequestRole) SetRoleType(v string) {
	o.RoleType = &v
}

// GetBaseRoleId returns the BaseRoleId field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetBaseRoleId() int64 {
	if o == nil || IsNil(o.BaseRoleId) {
		var ret int64
		return ret
	}
	return *o.BaseRoleId
}

// GetBaseRoleIdOk returns a tuple with the BaseRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetBaseRoleIdOk() (*int64, bool) {
	if o == nil || IsNil(o.BaseRoleId) {
		return nil, false
	}
	return o.BaseRoleId, true
}

// IsSetBaseRoleId returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetBaseRoleId() bool {
	if o != nil && !IsNil(o.BaseRoleId) {
		return true
	}

	return false
}

// SetBaseRoleId gets a reference to the given int64 and assigns it to the BaseRoleId field.
func (o *AddRolesRequestRole) SetBaseRoleId(v int64) {
	o.BaseRoleId = &v
}

// GetMultitenant returns the Multitenant field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetMultitenant() bool {
	if o == nil || IsNil(o.Multitenant) {
		var ret bool
		return ret
	}
	return *o.Multitenant
}

// GetMultitenantOk returns a tuple with the Multitenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetMultitenantOk() (*bool, bool) {
	if o == nil || IsNil(o.Multitenant) {
		return nil, false
	}
	return o.Multitenant, true
}

// IsSetMultitenant returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetMultitenant() bool {
	if o != nil && !IsNil(o.Multitenant) {
		return true
	}

	return false
}

// SetMultitenant gets a reference to the given bool and assigns it to the Multitenant field.
func (o *AddRolesRequestRole) SetMultitenant(v bool) {
	o.Multitenant = &v
}

// GetMultitenantLocked returns the MultitenantLocked field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetMultitenantLocked() bool {
	if o == nil || IsNil(o.MultitenantLocked) {
		var ret bool
		return ret
	}
	return *o.MultitenantLocked
}

// GetMultitenantLockedOk returns a tuple with the MultitenantLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetMultitenantLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.MultitenantLocked) {
		return nil, false
	}
	return o.MultitenantLocked, true
}

// IsSetMultitenantLocked returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetMultitenantLocked() bool {
	if o != nil && !IsNil(o.MultitenantLocked) {
		return true
	}

	return false
}

// SetMultitenantLocked gets a reference to the given bool and assigns it to the MultitenantLocked field.
func (o *AddRolesRequestRole) SetMultitenantLocked(v bool) {
	o.MultitenantLocked = &v
}

// GetDefaultPersona returns the DefaultPersona field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddRolesRequestRole) GetDefaultPersona() string {
	if o == nil || IsNil(o.DefaultPersona.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultPersona.Get()
}

// GetDefaultPersonaOk returns a tuple with the DefaultPersona field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddRolesRequestRole) GetDefaultPersonaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultPersona.Get(), o.DefaultPersona.IsSet()
}

// IsSetDefaultPersona returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetDefaultPersona() bool {
	if o != nil && o.DefaultPersona.IsSet() {
		return true
	}

	return false
}

// SetDefaultPersona gets a reference to the given NullableString and assigns it to the DefaultPersona field.
func (o *AddRolesRequestRole) SetDefaultPersona(v string) {
	o.DefaultPersona.Set(&v)
}

// SetDefaultPersonaNil sets the value for DefaultPersona to be an explicit nil
func (o *AddRolesRequestRole) SetDefaultPersonaNil() {
	o.DefaultPersona.Set(nil)
}

// UnsetDefaultPersona ensures that no value is present for DefaultPersona, not even an explicit nil
func (o *AddRolesRequestRole) UnsetDefaultPersona() {
	o.DefaultPersona.Unset()
}

// GetFeaturePermissions returns the FeaturePermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetFeaturePermissions() []AddRolesRequestRoleFeaturePermissionsInner {
	if o == nil || IsNil(o.FeaturePermissions) {
		var ret []AddRolesRequestRoleFeaturePermissionsInner
		return ret
	}
	return o.FeaturePermissions
}

// GetFeaturePermissionsOk returns a tuple with the FeaturePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetFeaturePermissionsOk() ([]AddRolesRequestRoleFeaturePermissionsInner, bool) {
	if o == nil || IsNil(o.FeaturePermissions) {
		return nil, false
	}
	return o.FeaturePermissions, true
}

// IsSetFeaturePermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetFeaturePermissions() bool {
	if o != nil && !IsNil(o.FeaturePermissions) {
		return true
	}

	return false
}

// SetFeaturePermissions gets a reference to the given []AddRolesRequestRoleFeaturePermissionsInner and assigns it to the FeaturePermissions field.
func (o *AddRolesRequestRole) SetFeaturePermissions(v []AddRolesRequestRoleFeaturePermissionsInner) {
	o.FeaturePermissions = v
}

// GetGlobalSiteAccess returns the GlobalSiteAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalSiteAccess() string {
	if o == nil || IsNil(o.GlobalSiteAccess) {
		var ret string
		return ret
	}
	return *o.GlobalSiteAccess
}

// GetGlobalSiteAccessOk returns a tuple with the GlobalSiteAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalSiteAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalSiteAccess) {
		return nil, false
	}
	return o.GlobalSiteAccess, true
}

// IsSetGlobalSiteAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalSiteAccess() bool {
	if o != nil && !IsNil(o.GlobalSiteAccess) {
		return true
	}

	return false
}

// SetGlobalSiteAccess gets a reference to the given string and assigns it to the GlobalSiteAccess field.
func (o *AddRolesRequestRole) SetGlobalSiteAccess(v string) {
	o.GlobalSiteAccess = &v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetSites() []AddRolesRequestRoleSitesInner {
	if o == nil || IsNil(o.Sites) {
		var ret []AddRolesRequestRoleSitesInner
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetSitesOk() ([]AddRolesRequestRoleSitesInner, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// IsSetSites returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []AddRolesRequestRoleSitesInner and assigns it to the Sites field.
func (o *AddRolesRequestRole) SetSites(v []AddRolesRequestRoleSitesInner) {
	o.Sites = v
}

// GetGlobalZoneAccess returns the GlobalZoneAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalZoneAccess() string {
	if o == nil || IsNil(o.GlobalZoneAccess) {
		var ret string
		return ret
	}
	return *o.GlobalZoneAccess
}

// GetGlobalZoneAccessOk returns a tuple with the GlobalZoneAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalZoneAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalZoneAccess) {
		return nil, false
	}
	return o.GlobalZoneAccess, true
}

// IsSetGlobalZoneAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalZoneAccess() bool {
	if o != nil && !IsNil(o.GlobalZoneAccess) {
		return true
	}

	return false
}

// SetGlobalZoneAccess gets a reference to the given string and assigns it to the GlobalZoneAccess field.
func (o *AddRolesRequestRole) SetGlobalZoneAccess(v string) {
	o.GlobalZoneAccess = &v
}

// GetZones returns the Zones field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetZones() []AddRolesRequestRoleZonesInner {
	if o == nil || IsNil(o.Zones) {
		var ret []AddRolesRequestRoleZonesInner
		return ret
	}
	return o.Zones
}

// GetZonesOk returns a tuple with the Zones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetZonesOk() ([]AddRolesRequestRoleZonesInner, bool) {
	if o == nil || IsNil(o.Zones) {
		return nil, false
	}
	return o.Zones, true
}

// IsSetZones returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetZones() bool {
	if o != nil && !IsNil(o.Zones) {
		return true
	}

	return false
}

// SetZones gets a reference to the given []AddRolesRequestRoleZonesInner and assigns it to the Zones field.
func (o *AddRolesRequestRole) SetZones(v []AddRolesRequestRoleZonesInner) {
	o.Zones = v
}

// GetGlobalInstanceTypeAccess returns the GlobalInstanceTypeAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalInstanceTypeAccess() string {
	if o == nil || IsNil(o.GlobalInstanceTypeAccess) {
		var ret string
		return ret
	}
	return *o.GlobalInstanceTypeAccess
}

// GetGlobalInstanceTypeAccessOk returns a tuple with the GlobalInstanceTypeAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalInstanceTypeAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalInstanceTypeAccess) {
		return nil, false
	}
	return o.GlobalInstanceTypeAccess, true
}

// IsSetGlobalInstanceTypeAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalInstanceTypeAccess() bool {
	if o != nil && !IsNil(o.GlobalInstanceTypeAccess) {
		return true
	}

	return false
}

// SetGlobalInstanceTypeAccess gets a reference to the given string and assigns it to the GlobalInstanceTypeAccess field.
func (o *AddRolesRequestRole) SetGlobalInstanceTypeAccess(v string) {
	o.GlobalInstanceTypeAccess = &v
}

// GetInstanceTypePermissions returns the InstanceTypePermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetInstanceTypePermissions() []AddRolesRequestRoleInstanceTypePermissionsInner {
	if o == nil || IsNil(o.InstanceTypePermissions) {
		var ret []AddRolesRequestRoleInstanceTypePermissionsInner
		return ret
	}
	return o.InstanceTypePermissions
}

// GetInstanceTypePermissionsOk returns a tuple with the InstanceTypePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetInstanceTypePermissionsOk() ([]AddRolesRequestRoleInstanceTypePermissionsInner, bool) {
	if o == nil || IsNil(o.InstanceTypePermissions) {
		return nil, false
	}
	return o.InstanceTypePermissions, true
}

// IsSetInstanceTypePermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetInstanceTypePermissions() bool {
	if o != nil && !IsNil(o.InstanceTypePermissions) {
		return true
	}

	return false
}

// SetInstanceTypePermissions gets a reference to the given []AddRolesRequestRoleInstanceTypePermissionsInner and assigns it to the InstanceTypePermissions field.
func (o *AddRolesRequestRole) SetInstanceTypePermissions(v []AddRolesRequestRoleInstanceTypePermissionsInner) {
	o.InstanceTypePermissions = v
}

// GetGlobalAppTemplateAccess returns the GlobalAppTemplateAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalAppTemplateAccess() string {
	if o == nil || IsNil(o.GlobalAppTemplateAccess) {
		var ret string
		return ret
	}
	return *o.GlobalAppTemplateAccess
}

// GetGlobalAppTemplateAccessOk returns a tuple with the GlobalAppTemplateAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalAppTemplateAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalAppTemplateAccess) {
		return nil, false
	}
	return o.GlobalAppTemplateAccess, true
}

// IsSetGlobalAppTemplateAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalAppTemplateAccess() bool {
	if o != nil && !IsNil(o.GlobalAppTemplateAccess) {
		return true
	}

	return false
}

// SetGlobalAppTemplateAccess gets a reference to the given string and assigns it to the GlobalAppTemplateAccess field.
func (o *AddRolesRequestRole) SetGlobalAppTemplateAccess(v string) {
	o.GlobalAppTemplateAccess = &v
}

// GetAppTemplatePermissions returns the AppTemplatePermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetAppTemplatePermissions() []AddRolesRequestRoleAppTemplatePermissionsInner {
	if o == nil || IsNil(o.AppTemplatePermissions) {
		var ret []AddRolesRequestRoleAppTemplatePermissionsInner
		return ret
	}
	return o.AppTemplatePermissions
}

// GetAppTemplatePermissionsOk returns a tuple with the AppTemplatePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetAppTemplatePermissionsOk() ([]AddRolesRequestRoleAppTemplatePermissionsInner, bool) {
	if o == nil || IsNil(o.AppTemplatePermissions) {
		return nil, false
	}
	return o.AppTemplatePermissions, true
}

// IsSetAppTemplatePermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetAppTemplatePermissions() bool {
	if o != nil && !IsNil(o.AppTemplatePermissions) {
		return true
	}

	return false
}

// SetAppTemplatePermissions gets a reference to the given []AddRolesRequestRoleAppTemplatePermissionsInner and assigns it to the AppTemplatePermissions field.
func (o *AddRolesRequestRole) SetAppTemplatePermissions(v []AddRolesRequestRoleAppTemplatePermissionsInner) {
	o.AppTemplatePermissions = v
}

// GetGlobalCatalogItemTypeAccess returns the GlobalCatalogItemTypeAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalCatalogItemTypeAccess() string {
	if o == nil || IsNil(o.GlobalCatalogItemTypeAccess) {
		var ret string
		return ret
	}
	return *o.GlobalCatalogItemTypeAccess
}

// GetGlobalCatalogItemTypeAccessOk returns a tuple with the GlobalCatalogItemTypeAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalCatalogItemTypeAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalCatalogItemTypeAccess) {
		return nil, false
	}
	return o.GlobalCatalogItemTypeAccess, true
}

// IsSetGlobalCatalogItemTypeAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalCatalogItemTypeAccess() bool {
	if o != nil && !IsNil(o.GlobalCatalogItemTypeAccess) {
		return true
	}

	return false
}

// SetGlobalCatalogItemTypeAccess gets a reference to the given string and assigns it to the GlobalCatalogItemTypeAccess field.
func (o *AddRolesRequestRole) SetGlobalCatalogItemTypeAccess(v string) {
	o.GlobalCatalogItemTypeAccess = &v
}

// GetCatalogItemTypePermissions returns the CatalogItemTypePermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetCatalogItemTypePermissions() []AddRolesRequestRoleCatalogItemTypePermissionsInner {
	if o == nil || IsNil(o.CatalogItemTypePermissions) {
		var ret []AddRolesRequestRoleCatalogItemTypePermissionsInner
		return ret
	}
	return o.CatalogItemTypePermissions
}

// GetCatalogItemTypePermissionsOk returns a tuple with the CatalogItemTypePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetCatalogItemTypePermissionsOk() ([]AddRolesRequestRoleCatalogItemTypePermissionsInner, bool) {
	if o == nil || IsNil(o.CatalogItemTypePermissions) {
		return nil, false
	}
	return o.CatalogItemTypePermissions, true
}

// IsSetCatalogItemTypePermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetCatalogItemTypePermissions() bool {
	if o != nil && !IsNil(o.CatalogItemTypePermissions) {
		return true
	}

	return false
}

// SetCatalogItemTypePermissions gets a reference to the given []AddRolesRequestRoleCatalogItemTypePermissionsInner and assigns it to the CatalogItemTypePermissions field.
func (o *AddRolesRequestRole) SetCatalogItemTypePermissions(v []AddRolesRequestRoleCatalogItemTypePermissionsInner) {
	o.CatalogItemTypePermissions = v
}

// GetGlobalPersonaAccess returns the GlobalPersonaAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalPersonaAccess() string {
	if o == nil || IsNil(o.GlobalPersonaAccess) {
		var ret string
		return ret
	}
	return *o.GlobalPersonaAccess
}

// GetGlobalPersonaAccessOk returns a tuple with the GlobalPersonaAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalPersonaAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalPersonaAccess) {
		return nil, false
	}
	return o.GlobalPersonaAccess, true
}

// IsSetGlobalPersonaAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalPersonaAccess() bool {
	if o != nil && !IsNil(o.GlobalPersonaAccess) {
		return true
	}

	return false
}

// SetGlobalPersonaAccess gets a reference to the given string and assigns it to the GlobalPersonaAccess field.
func (o *AddRolesRequestRole) SetGlobalPersonaAccess(v string) {
	o.GlobalPersonaAccess = &v
}

// GetPersonaPermissions returns the PersonaPermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetPersonaPermissions() []AddRolesRequestRolePersonaPermissionsInner {
	if o == nil || IsNil(o.PersonaPermissions) {
		var ret []AddRolesRequestRolePersonaPermissionsInner
		return ret
	}
	return o.PersonaPermissions
}

// GetPersonaPermissionsOk returns a tuple with the PersonaPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetPersonaPermissionsOk() ([]AddRolesRequestRolePersonaPermissionsInner, bool) {
	if o == nil || IsNil(o.PersonaPermissions) {
		return nil, false
	}
	return o.PersonaPermissions, true
}

// IsSetPersonaPermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetPersonaPermissions() bool {
	if o != nil && !IsNil(o.PersonaPermissions) {
		return true
	}

	return false
}

// SetPersonaPermissions gets a reference to the given []AddRolesRequestRolePersonaPermissionsInner and assigns it to the PersonaPermissions field.
func (o *AddRolesRequestRole) SetPersonaPermissions(v []AddRolesRequestRolePersonaPermissionsInner) {
	o.PersonaPermissions = v
}

// GetGlobalVdiPoolAccess returns the GlobalVdiPoolAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalVdiPoolAccess() string {
	if o == nil || IsNil(o.GlobalVdiPoolAccess) {
		var ret string
		return ret
	}
	return *o.GlobalVdiPoolAccess
}

// GetGlobalVdiPoolAccessOk returns a tuple with the GlobalVdiPoolAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalVdiPoolAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalVdiPoolAccess) {
		return nil, false
	}
	return o.GlobalVdiPoolAccess, true
}

// IsSetGlobalVdiPoolAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalVdiPoolAccess() bool {
	if o != nil && !IsNil(o.GlobalVdiPoolAccess) {
		return true
	}

	return false
}

// SetGlobalVdiPoolAccess gets a reference to the given string and assigns it to the GlobalVdiPoolAccess field.
func (o *AddRolesRequestRole) SetGlobalVdiPoolAccess(v string) {
	o.GlobalVdiPoolAccess = &v
}

// GetVdiPoolPermissions returns the VdiPoolPermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetVdiPoolPermissions() []AddRolesRequestRoleVdiPoolPermissionsInner {
	if o == nil || IsNil(o.VdiPoolPermissions) {
		var ret []AddRolesRequestRoleVdiPoolPermissionsInner
		return ret
	}
	return o.VdiPoolPermissions
}

// GetVdiPoolPermissionsOk returns a tuple with the VdiPoolPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetVdiPoolPermissionsOk() ([]AddRolesRequestRoleVdiPoolPermissionsInner, bool) {
	if o == nil || IsNil(o.VdiPoolPermissions) {
		return nil, false
	}
	return o.VdiPoolPermissions, true
}

// IsSetVdiPoolPermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetVdiPoolPermissions() bool {
	if o != nil && !IsNil(o.VdiPoolPermissions) {
		return true
	}

	return false
}

// SetVdiPoolPermissions gets a reference to the given []AddRolesRequestRoleVdiPoolPermissionsInner and assigns it to the VdiPoolPermissions field.
func (o *AddRolesRequestRole) SetVdiPoolPermissions(v []AddRolesRequestRoleVdiPoolPermissionsInner) {
	o.VdiPoolPermissions = v
}

// GetGlobalReportTypeAccess returns the GlobalReportTypeAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalReportTypeAccess() string {
	if o == nil || IsNil(o.GlobalReportTypeAccess) {
		var ret string
		return ret
	}
	return *o.GlobalReportTypeAccess
}

// GetGlobalReportTypeAccessOk returns a tuple with the GlobalReportTypeAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalReportTypeAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalReportTypeAccess) {
		return nil, false
	}
	return o.GlobalReportTypeAccess, true
}

// IsSetGlobalReportTypeAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalReportTypeAccess() bool {
	if o != nil && !IsNil(o.GlobalReportTypeAccess) {
		return true
	}

	return false
}

// SetGlobalReportTypeAccess gets a reference to the given string and assigns it to the GlobalReportTypeAccess field.
func (o *AddRolesRequestRole) SetGlobalReportTypeAccess(v string) {
	o.GlobalReportTypeAccess = &v
}

// GetReportTypePermissions returns the ReportTypePermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetReportTypePermissions() []AddRolesRequestRoleReportTypePermissionsInner {
	if o == nil || IsNil(o.ReportTypePermissions) {
		var ret []AddRolesRequestRoleReportTypePermissionsInner
		return ret
	}
	return o.ReportTypePermissions
}

// GetReportTypePermissionsOk returns a tuple with the ReportTypePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetReportTypePermissionsOk() ([]AddRolesRequestRoleReportTypePermissionsInner, bool) {
	if o == nil || IsNil(o.ReportTypePermissions) {
		return nil, false
	}
	return o.ReportTypePermissions, true
}

// IsSetReportTypePermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetReportTypePermissions() bool {
	if o != nil && !IsNil(o.ReportTypePermissions) {
		return true
	}

	return false
}

// SetReportTypePermissions gets a reference to the given []AddRolesRequestRoleReportTypePermissionsInner and assigns it to the ReportTypePermissions field.
func (o *AddRolesRequestRole) SetReportTypePermissions(v []AddRolesRequestRoleReportTypePermissionsInner) {
	o.ReportTypePermissions = v
}

// GetGlobalTaskAccess returns the GlobalTaskAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalTaskAccess() string {
	if o == nil || IsNil(o.GlobalTaskAccess) {
		var ret string
		return ret
	}
	return *o.GlobalTaskAccess
}

// GetGlobalTaskAccessOk returns a tuple with the GlobalTaskAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalTaskAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalTaskAccess) {
		return nil, false
	}
	return o.GlobalTaskAccess, true
}

// IsSetGlobalTaskAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalTaskAccess() bool {
	if o != nil && !IsNil(o.GlobalTaskAccess) {
		return true
	}

	return false
}

// SetGlobalTaskAccess gets a reference to the given string and assigns it to the GlobalTaskAccess field.
func (o *AddRolesRequestRole) SetGlobalTaskAccess(v string) {
	o.GlobalTaskAccess = &v
}

// GetTaskPermissions returns the TaskPermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetTaskPermissions() []AddRolesRequestRoleTaskPermissionsInner {
	if o == nil || IsNil(o.TaskPermissions) {
		var ret []AddRolesRequestRoleTaskPermissionsInner
		return ret
	}
	return o.TaskPermissions
}

// GetTaskPermissionsOk returns a tuple with the TaskPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetTaskPermissionsOk() ([]AddRolesRequestRoleTaskPermissionsInner, bool) {
	if o == nil || IsNil(o.TaskPermissions) {
		return nil, false
	}
	return o.TaskPermissions, true
}

// IsSetTaskPermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetTaskPermissions() bool {
	if o != nil && !IsNil(o.TaskPermissions) {
		return true
	}

	return false
}

// SetTaskPermissions gets a reference to the given []AddRolesRequestRoleTaskPermissionsInner and assigns it to the TaskPermissions field.
func (o *AddRolesRequestRole) SetTaskPermissions(v []AddRolesRequestRoleTaskPermissionsInner) {
	o.TaskPermissions = v
}

// GetGlobalTaskSetAccess returns the GlobalTaskSetAccess field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetGlobalTaskSetAccess() string {
	if o == nil || IsNil(o.GlobalTaskSetAccess) {
		var ret string
		return ret
	}
	return *o.GlobalTaskSetAccess
}

// GetGlobalTaskSetAccessOk returns a tuple with the GlobalTaskSetAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetGlobalTaskSetAccessOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalTaskSetAccess) {
		return nil, false
	}
	return o.GlobalTaskSetAccess, true
}

// IsSetGlobalTaskSetAccess returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetGlobalTaskSetAccess() bool {
	if o != nil && !IsNil(o.GlobalTaskSetAccess) {
		return true
	}

	return false
}

// SetGlobalTaskSetAccess gets a reference to the given string and assigns it to the GlobalTaskSetAccess field.
func (o *AddRolesRequestRole) SetGlobalTaskSetAccess(v string) {
	o.GlobalTaskSetAccess = &v
}

// GetTaskSetPermissions returns the TaskSetPermissions field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetTaskSetPermissions() []AddRolesRequestRoleTaskSetPermissionsInner {
	if o == nil || IsNil(o.TaskSetPermissions) {
		var ret []AddRolesRequestRoleTaskSetPermissionsInner
		return ret
	}
	return o.TaskSetPermissions
}

// GetTaskSetPermissionsOk returns a tuple with the TaskSetPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetTaskSetPermissionsOk() ([]AddRolesRequestRoleTaskSetPermissionsInner, bool) {
	if o == nil || IsNil(o.TaskSetPermissions) {
		return nil, false
	}
	return o.TaskSetPermissions, true
}

// IsSetTaskSetPermissions returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetTaskSetPermissions() bool {
	if o != nil && !IsNil(o.TaskSetPermissions) {
		return true
	}

	return false
}

// SetTaskSetPermissions gets a reference to the given []AddRolesRequestRoleTaskSetPermissionsInner and assigns it to the TaskSetPermissions field.
func (o *AddRolesRequestRole) SetTaskSetPermissions(v []AddRolesRequestRoleTaskSetPermissionsInner) {
	o.TaskSetPermissions = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *AddRolesRequestRole) GetOwner() int64 {
	if o == nil || IsNil(o.Owner) {
		var ret int64
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRolesRequestRole) GetOwnerOk() (*int64, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// IsSetOwner returns a boolean if a field has been set.
func (o *AddRolesRequestRole) IsSetOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given int64 and assigns it to the Owner field.
func (o *AddRolesRequestRole) SetOwner(v int64) {
	o.Owner = &v
}

func (o AddRolesRequestRole) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddRolesRequestRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authority"] = o.Authority
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.LandingUrl.IsSet() {
		toSerialize["landingUrl"] = o.LandingUrl.Get()
	}
	if !IsNil(o.RoleType) {
		toSerialize["roleType"] = o.RoleType
	}
	if !IsNil(o.BaseRoleId) {
		toSerialize["baseRoleId"] = o.BaseRoleId
	}
	if !IsNil(o.Multitenant) {
		toSerialize["multitenant"] = o.Multitenant
	}
	if !IsNil(o.MultitenantLocked) {
		toSerialize["multitenantLocked"] = o.MultitenantLocked
	}
	if o.DefaultPersona.IsSet() {
		toSerialize["defaultPersona"] = o.DefaultPersona.Get()
	}
	if !IsNil(o.FeaturePermissions) {
		toSerialize["featurePermissions"] = o.FeaturePermissions
	}
	if !IsNil(o.GlobalSiteAccess) {
		toSerialize["globalSiteAccess"] = o.GlobalSiteAccess
	}
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	if !IsNil(o.GlobalZoneAccess) {
		toSerialize["globalZoneAccess"] = o.GlobalZoneAccess
	}
	if !IsNil(o.Zones) {
		toSerialize["zones"] = o.Zones
	}
	if !IsNil(o.GlobalInstanceTypeAccess) {
		toSerialize["globalInstanceTypeAccess"] = o.GlobalInstanceTypeAccess
	}
	if !IsNil(o.InstanceTypePermissions) {
		toSerialize["instanceTypePermissions"] = o.InstanceTypePermissions
	}
	if !IsNil(o.GlobalAppTemplateAccess) {
		toSerialize["globalAppTemplateAccess"] = o.GlobalAppTemplateAccess
	}
	if !IsNil(o.AppTemplatePermissions) {
		toSerialize["appTemplatePermissions"] = o.AppTemplatePermissions
	}
	if !IsNil(o.GlobalCatalogItemTypeAccess) {
		toSerialize["globalCatalogItemTypeAccess"] = o.GlobalCatalogItemTypeAccess
	}
	if !IsNil(o.CatalogItemTypePermissions) {
		toSerialize["catalogItemTypePermissions"] = o.CatalogItemTypePermissions
	}
	if !IsNil(o.GlobalPersonaAccess) {
		toSerialize["globalPersonaAccess"] = o.GlobalPersonaAccess
	}
	if !IsNil(o.PersonaPermissions) {
		toSerialize["personaPermissions"] = o.PersonaPermissions
	}
	if !IsNil(o.GlobalVdiPoolAccess) {
		toSerialize["globalVdiPoolAccess"] = o.GlobalVdiPoolAccess
	}
	if !IsNil(o.VdiPoolPermissions) {
		toSerialize["vdiPoolPermissions"] = o.VdiPoolPermissions
	}
	if !IsNil(o.GlobalReportTypeAccess) {
		toSerialize["globalReportTypeAccess"] = o.GlobalReportTypeAccess
	}
	if !IsNil(o.ReportTypePermissions) {
		toSerialize["reportTypePermissions"] = o.ReportTypePermissions
	}
	if !IsNil(o.GlobalTaskAccess) {
		toSerialize["globalTaskAccess"] = o.GlobalTaskAccess
	}
	if !IsNil(o.TaskPermissions) {
		toSerialize["taskPermissions"] = o.TaskPermissions
	}
	if !IsNil(o.GlobalTaskSetAccess) {
		toSerialize["globalTaskSetAccess"] = o.GlobalTaskSetAccess
	}
	if !IsNil(o.TaskSetPermissions) {
		toSerialize["taskSetPermissions"] = o.TaskSetPermissions
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *AddRolesRequestRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authority",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddRolesRequestRole := _AddRolesRequestRole{}

	err = json.Unmarshal(data, &varAddRolesRequestRole)

	if err != nil {
		return err
	}

	*o = AddRolesRequestRole(varAddRolesRequestRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authority")
		delete(additionalProperties, "description")
		delete(additionalProperties, "landingUrl")
		delete(additionalProperties, "roleType")
		delete(additionalProperties, "baseRoleId")
		delete(additionalProperties, "multitenant")
		delete(additionalProperties, "multitenantLocked")
		delete(additionalProperties, "defaultPersona")
		delete(additionalProperties, "featurePermissions")
		delete(additionalProperties, "globalSiteAccess")
		delete(additionalProperties, "sites")
		delete(additionalProperties, "globalZoneAccess")
		delete(additionalProperties, "zones")
		delete(additionalProperties, "globalInstanceTypeAccess")
		delete(additionalProperties, "instanceTypePermissions")
		delete(additionalProperties, "globalAppTemplateAccess")
		delete(additionalProperties, "appTemplatePermissions")
		delete(additionalProperties, "globalCatalogItemTypeAccess")
		delete(additionalProperties, "catalogItemTypePermissions")
		delete(additionalProperties, "globalPersonaAccess")
		delete(additionalProperties, "personaPermissions")
		delete(additionalProperties, "globalVdiPoolAccess")
		delete(additionalProperties, "vdiPoolPermissions")
		delete(additionalProperties, "globalReportTypeAccess")
		delete(additionalProperties, "reportTypePermissions")
		delete(additionalProperties, "globalTaskAccess")
		delete(additionalProperties, "taskPermissions")
		delete(additionalProperties, "globalTaskSetAccess")
		delete(additionalProperties, "taskSetPermissions")
		delete(additionalProperties, "owner")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddRolesRequestRole struct {
	value *AddRolesRequestRole
	isSet bool
}

func (v NullableAddRolesRequestRole) Get() *AddRolesRequestRole {
	return v.value
}

func (v *NullableAddRolesRequestRole) Set(val *AddRolesRequestRole) {
	v.value = val
	v.isSet = true
}

func (v NullableAddRolesRequestRole) IsSet() bool {
	return v.isSet
}

func (v *NullableAddRolesRequestRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddRolesRequestRole(val *AddRolesRequestRole) *NullableAddRolesRequestRole {
	return &NullableAddRolesRequestRole{value: val, isSet: true}
}

func (v NullableAddRolesRequestRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddRolesRequestRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
