/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetNetworkDomains200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkDomains200Response{}

// GetNetworkDomains200Response struct for GetNetworkDomains200Response
type GetNetworkDomains200Response struct {
	NetworkDomains       interface{}                       `json:"networkDomains,omitempty"`
	Meta                 *ListActivity200ResponseAllOfMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetNetworkDomains200Response GetNetworkDomains200Response

// NewGetNetworkDomains200Response instantiates a new GetNetworkDomains200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkDomains200Response() *GetNetworkDomains200Response {
	this := GetNetworkDomains200Response{}
	return &this
}

// NewGetNetworkDomains200ResponseWithDefaults instantiates a new GetNetworkDomains200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkDomains200ResponseWithDefaults() *GetNetworkDomains200Response {
	this := GetNetworkDomains200Response{}
	return &this
}

// GetNetworkDomains returns the NetworkDomains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetNetworkDomains200Response) GetNetworkDomains() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.NetworkDomains
}

// GetNetworkDomainsOk returns a tuple with the NetworkDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetNetworkDomains200Response) GetNetworkDomainsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NetworkDomains) {
		return nil, false
	}
	return &o.NetworkDomains, true
}

// IsSetNetworkDomains returns a boolean if a field has been set.
func (o *GetNetworkDomains200Response) IsSetNetworkDomains() bool {
	if o != nil && !IsNil(o.NetworkDomains) {
		return true
	}

	return false
}

// SetNetworkDomains gets a reference to the given interface{} and assigns it to the NetworkDomains field.
func (o *GetNetworkDomains200Response) SetNetworkDomains(v interface{}) {
	o.NetworkDomains = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetNetworkDomains200Response) GetMeta() ListActivity200ResponseAllOfMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ListActivity200ResponseAllOfMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkDomains200Response) GetMetaOk() (*ListActivity200ResponseAllOfMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// IsSetMeta returns a boolean if a field has been set.
func (o *GetNetworkDomains200Response) IsSetMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ListActivity200ResponseAllOfMeta and assigns it to the Meta field.
func (o *GetNetworkDomains200Response) SetMeta(v ListActivity200ResponseAllOfMeta) {
	o.Meta = &v
}

func (o GetNetworkDomains200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkDomains200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NetworkDomains != nil {
		toSerialize["networkDomains"] = o.NetworkDomains
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *GetNetworkDomains200Response) UnmarshalJSON(data []byte) (err error) {
	varGetNetworkDomains200Response := _GetNetworkDomains200Response{}

	err = json.Unmarshal(data, &varGetNetworkDomains200Response)

	if err != nil {
		return err
	}

	*o = GetNetworkDomains200Response(varGetNetworkDomains200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "networkDomains")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetNetworkDomains200Response struct {
	value *GetNetworkDomains200Response
	isSet bool
}

func (v NullableGetNetworkDomains200Response) Get() *GetNetworkDomains200Response {
	return v.value
}

func (v *NullableGetNetworkDomains200Response) Set(val *GetNetworkDomains200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkDomains200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkDomains200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkDomains200Response(val *GetNetworkDomains200Response) *NullableGetNetworkDomains200Response {
	return &NullableGetNetworkDomains200Response{value: val, isSet: true}
}

func (v NullableGetNetworkDomains200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkDomains200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
