/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.7
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

// checks if the ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner{}

// ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner struct for ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner
type ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner struct {
	Id                   *int64                                                                         `json:"id,omitempty"`
	LoadBalancer         *ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer `json:"loadBalancer,omitempty"`
	Instance             NullableString                                                                 `json:"instance,omitempty"`
	Description          NullableString                                                                 `json:"description,omitempty"`
	InternalId           *string                                                                        `json:"internalId,omitempty"`
	ExternalId           *string                                                                        `json:"externalId,omitempty"`
	DateCreated          *time.Time                                                                     `json:"dateCreated,omitempty"`
	LastUpdated          *time.Time                                                                     `json:"lastUpdated,omitempty"`
	Active               *bool                                                                          `json:"active,omitempty"`
	Sticky               *bool                                                                          `json:"sticky,omitempty"`
	SslEnabled           NullableString                                                                 `json:"sslEnabled,omitempty"`
	ExternalAddress      *bool                                                                          `json:"externalAddress,omitempty"`
	BackendPort          NullableString                                                                 `json:"backendPort,omitempty"`
	VipType              NullableString                                                                 `json:"vipType,omitempty"`
	VipAddress           *string                                                                        `json:"vipAddress,omitempty"`
	VipHostname          NullableString                                                                 `json:"vipHostname,omitempty"`
	VipProtocol          *string                                                                        `json:"vipProtocol,omitempty"`
	VipScheme            NullableString                                                                 `json:"vipScheme,omitempty"`
	VipMode              NullableString                                                                 `json:"vipMode,omitempty"`
	VipName              *string                                                                        `json:"vipName,omitempty"`
	VipPort              *int64                                                                         `json:"vipPort,omitempty"`
	VipSticky            NullableString                                                                 `json:"vipSticky,omitempty"`
	VipBalance           NullableString                                                                 `json:"vipBalance,omitempty"`
	ServicePort          NullableString                                                                 `json:"servicePort,omitempty"`
	SourceAddress        NullableString                                                                 `json:"sourceAddress,omitempty"`
	SslCert              *GetAlerts200ResponseAllOfCheckGroupsInnerInstance                             `json:"sslCert,omitempty"`
	SslMode              NullableString                                                                 `json:"sslMode,omitempty"`
	SslRedirectMode      NullableString                                                                 `json:"sslRedirectMode,omitempty"`
	VipShared            *bool                                                                          `json:"vipShared,omitempty"`
	VipDirectAddress     NullableString                                                                 `json:"vipDirectAddress,omitempty"`
	ServerName           NullableString                                                                 `json:"serverName,omitempty"`
	PoolName             NullableString                                                                 `json:"poolName,omitempty"`
	Removing             *bool                                                                          `json:"removing,omitempty"`
	VipSource            *string                                                                        `json:"vipSource,omitempty"`
	ExtraConfig          NullableString                                                                 `json:"extraConfig,omitempty"`
	ServiceAccess        NullableString                                                                 `json:"serviceAccess,omitempty"`
	NetworkId            NullableString                                                                 `json:"networkId,omitempty"`
	SubnetId             NullableString                                                                 `json:"subnetId,omitempty"`
	ExternalPortId       NullableString                                                                 `json:"externalPortId,omitempty"`
	Status               *string                                                                        `json:"status,omitempty"`
	VipStatus            *string                                                                        `json:"vipStatus,omitempty"`
	AdditionalProperties map[string]interface{}                                                         `json:",remain"`
}

type _ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner

// NewListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner instantiates a new ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner() *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner {
	this := ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner{}
	return &this
}

// NewListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInnerWithDefaults instantiates a new ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInnerWithDefaults() *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner {
	this := ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetId(v int64) {
	o.Id = &v
}

// GetLoadBalancer returns the LoadBalancer field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetLoadBalancer() ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer {
	if o == nil || IsNil(o.LoadBalancer) {
		var ret ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer
		return ret
	}
	return *o.LoadBalancer
}

// GetLoadBalancerOk returns a tuple with the LoadBalancer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetLoadBalancerOk() (*ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer, bool) {
	if o == nil || IsNil(o.LoadBalancer) {
		return nil, false
	}
	return o.LoadBalancer, true
}

// IsSetLoadBalancer returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetLoadBalancer() bool {
	if o != nil && !IsNil(o.LoadBalancer) {
		return true
	}

	return false
}

// SetLoadBalancer gets a reference to the given ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer and assigns it to the LoadBalancer field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetLoadBalancer(v ListLoadBalancerMonitors200ResponseAllOfLoadBalancerMonitorsInnerLoadBalancer) {
	o.LoadBalancer = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetInstance() string {
	if o == nil || IsNil(o.Instance.Get()) {
		var ret string
		return ret
	}
	return *o.Instance.Get()
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instance.Get(), o.Instance.IsSet()
}

// IsSetInstance returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetInstance() bool {
	if o != nil && o.Instance.IsSet() {
		return true
	}

	return false
}

// SetInstance gets a reference to the given NullableString and assigns it to the Instance field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetInstance(v string) {
	o.Instance.Set(&v)
}

// SetInstanceNil sets the value for Instance to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetInstanceNil() {
	o.Instance.Set(nil)
}

// UnsetInstance ensures that no value is present for Instance, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetInstance() {
	o.Instance.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// IsSetDescription returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetDescription() {
	o.Description.Unset()
}

// GetInternalId returns the InternalId field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetInternalId() string {
	if o == nil || IsNil(o.InternalId) {
		var ret string
		return ret
	}
	return *o.InternalId
}

// GetInternalIdOk returns a tuple with the InternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetInternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.InternalId) {
		return nil, false
	}
	return o.InternalId, true
}

// IsSetInternalId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetInternalId() bool {
	if o != nil && !IsNil(o.InternalId) {
		return true
	}

	return false
}

// SetInternalId gets a reference to the given string and assigns it to the InternalId field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetInternalId(v string) {
	o.InternalId = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// IsSetExternalId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetDateCreated() time.Time {
	if o == nil || IsNil(o.DateCreated) {
		var ret time.Time
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetDateCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// IsSetDateCreated returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given time.Time and assigns it to the DateCreated field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetDateCreated(v time.Time) {
	o.DateCreated = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// IsSetLastUpdated returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// IsSetActive returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetActive(v bool) {
	o.Active = &v
}

// GetSticky returns the Sticky field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSticky() bool {
	if o == nil || IsNil(o.Sticky) {
		var ret bool
		return ret
	}
	return *o.Sticky
}

// GetStickyOk returns a tuple with the Sticky field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetStickyOk() (*bool, bool) {
	if o == nil || IsNil(o.Sticky) {
		return nil, false
	}
	return o.Sticky, true
}

// IsSetSticky returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSticky() bool {
	if o != nil && !IsNil(o.Sticky) {
		return true
	}

	return false
}

// SetSticky gets a reference to the given bool and assigns it to the Sticky field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSticky(v bool) {
	o.Sticky = &v
}

// GetSslEnabled returns the SslEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslEnabled() string {
	if o == nil || IsNil(o.SslEnabled.Get()) {
		var ret string
		return ret
	}
	return *o.SslEnabled.Get()
}

// GetSslEnabledOk returns a tuple with the SslEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslEnabledOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslEnabled.Get(), o.SslEnabled.IsSet()
}

// IsSetSslEnabled returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSslEnabled() bool {
	if o != nil && o.SslEnabled.IsSet() {
		return true
	}

	return false
}

// SetSslEnabled gets a reference to the given NullableString and assigns it to the SslEnabled field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslEnabled(v string) {
	o.SslEnabled.Set(&v)
}

// SetSslEnabledNil sets the value for SslEnabled to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslEnabledNil() {
	o.SslEnabled.Set(nil)
}

// UnsetSslEnabled ensures that no value is present for SslEnabled, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetSslEnabled() {
	o.SslEnabled.Unset()
}

// GetExternalAddress returns the ExternalAddress field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalAddress() bool {
	if o == nil || IsNil(o.ExternalAddress) {
		var ret bool
		return ret
	}
	return *o.ExternalAddress
}

// GetExternalAddressOk returns a tuple with the ExternalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.ExternalAddress) {
		return nil, false
	}
	return o.ExternalAddress, true
}

// IsSetExternalAddress returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetExternalAddress() bool {
	if o != nil && !IsNil(o.ExternalAddress) {
		return true
	}

	return false
}

// SetExternalAddress gets a reference to the given bool and assigns it to the ExternalAddress field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExternalAddress(v bool) {
	o.ExternalAddress = &v
}

// GetBackendPort returns the BackendPort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetBackendPort() string {
	if o == nil || IsNil(o.BackendPort.Get()) {
		var ret string
		return ret
	}
	return *o.BackendPort.Get()
}

// GetBackendPortOk returns a tuple with the BackendPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetBackendPortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackendPort.Get(), o.BackendPort.IsSet()
}

// IsSetBackendPort returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetBackendPort() bool {
	if o != nil && o.BackendPort.IsSet() {
		return true
	}

	return false
}

// SetBackendPort gets a reference to the given NullableString and assigns it to the BackendPort field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetBackendPort(v string) {
	o.BackendPort.Set(&v)
}

// SetBackendPortNil sets the value for BackendPort to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetBackendPortNil() {
	o.BackendPort.Set(nil)
}

// UnsetBackendPort ensures that no value is present for BackendPort, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetBackendPort() {
	o.BackendPort.Unset()
}

// GetVipType returns the VipType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipType() string {
	if o == nil || IsNil(o.VipType.Get()) {
		var ret string
		return ret
	}
	return *o.VipType.Get()
}

// GetVipTypeOk returns a tuple with the VipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipType.Get(), o.VipType.IsSet()
}

// IsSetVipType returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipType() bool {
	if o != nil && o.VipType.IsSet() {
		return true
	}

	return false
}

// SetVipType gets a reference to the given NullableString and assigns it to the VipType field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipType(v string) {
	o.VipType.Set(&v)
}

// SetVipTypeNil sets the value for VipType to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipTypeNil() {
	o.VipType.Set(nil)
}

// UnsetVipType ensures that no value is present for VipType, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipType() {
	o.VipType.Unset()
}

// GetVipAddress returns the VipAddress field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipAddress() string {
	if o == nil || IsNil(o.VipAddress) {
		var ret string
		return ret
	}
	return *o.VipAddress
}

// GetVipAddressOk returns a tuple with the VipAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipAddressOk() (*string, bool) {
	if o == nil || IsNil(o.VipAddress) {
		return nil, false
	}
	return o.VipAddress, true
}

// IsSetVipAddress returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipAddress() bool {
	if o != nil && !IsNil(o.VipAddress) {
		return true
	}

	return false
}

// SetVipAddress gets a reference to the given string and assigns it to the VipAddress field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipAddress(v string) {
	o.VipAddress = &v
}

// GetVipHostname returns the VipHostname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipHostname() string {
	if o == nil || IsNil(o.VipHostname.Get()) {
		var ret string
		return ret
	}
	return *o.VipHostname.Get()
}

// GetVipHostnameOk returns a tuple with the VipHostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipHostname.Get(), o.VipHostname.IsSet()
}

// IsSetVipHostname returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipHostname() bool {
	if o != nil && o.VipHostname.IsSet() {
		return true
	}

	return false
}

// SetVipHostname gets a reference to the given NullableString and assigns it to the VipHostname field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipHostname(v string) {
	o.VipHostname.Set(&v)
}

// SetVipHostnameNil sets the value for VipHostname to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipHostnameNil() {
	o.VipHostname.Set(nil)
}

// UnsetVipHostname ensures that no value is present for VipHostname, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipHostname() {
	o.VipHostname.Unset()
}

// GetVipProtocol returns the VipProtocol field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipProtocol() string {
	if o == nil || IsNil(o.VipProtocol) {
		var ret string
		return ret
	}
	return *o.VipProtocol
}

// GetVipProtocolOk returns a tuple with the VipProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.VipProtocol) {
		return nil, false
	}
	return o.VipProtocol, true
}

// IsSetVipProtocol returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipProtocol() bool {
	if o != nil && !IsNil(o.VipProtocol) {
		return true
	}

	return false
}

// SetVipProtocol gets a reference to the given string and assigns it to the VipProtocol field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipProtocol(v string) {
	o.VipProtocol = &v
}

// GetVipScheme returns the VipScheme field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipScheme() string {
	if o == nil || IsNil(o.VipScheme.Get()) {
		var ret string
		return ret
	}
	return *o.VipScheme.Get()
}

// GetVipSchemeOk returns a tuple with the VipScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipSchemeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipScheme.Get(), o.VipScheme.IsSet()
}

// IsSetVipScheme returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipScheme() bool {
	if o != nil && o.VipScheme.IsSet() {
		return true
	}

	return false
}

// SetVipScheme gets a reference to the given NullableString and assigns it to the VipScheme field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipScheme(v string) {
	o.VipScheme.Set(&v)
}

// SetVipSchemeNil sets the value for VipScheme to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipSchemeNil() {
	o.VipScheme.Set(nil)
}

// UnsetVipScheme ensures that no value is present for VipScheme, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipScheme() {
	o.VipScheme.Unset()
}

// GetVipMode returns the VipMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipMode() string {
	if o == nil || IsNil(o.VipMode.Get()) {
		var ret string
		return ret
	}
	return *o.VipMode.Get()
}

// GetVipModeOk returns a tuple with the VipMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipMode.Get(), o.VipMode.IsSet()
}

// IsSetVipMode returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipMode() bool {
	if o != nil && o.VipMode.IsSet() {
		return true
	}

	return false
}

// SetVipMode gets a reference to the given NullableString and assigns it to the VipMode field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipMode(v string) {
	o.VipMode.Set(&v)
}

// SetVipModeNil sets the value for VipMode to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipModeNil() {
	o.VipMode.Set(nil)
}

// UnsetVipMode ensures that no value is present for VipMode, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipMode() {
	o.VipMode.Unset()
}

// GetVipName returns the VipName field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipName() string {
	if o == nil || IsNil(o.VipName) {
		var ret string
		return ret
	}
	return *o.VipName
}

// GetVipNameOk returns a tuple with the VipName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipNameOk() (*string, bool) {
	if o == nil || IsNil(o.VipName) {
		return nil, false
	}
	return o.VipName, true
}

// IsSetVipName returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipName() bool {
	if o != nil && !IsNil(o.VipName) {
		return true
	}

	return false
}

// SetVipName gets a reference to the given string and assigns it to the VipName field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipName(v string) {
	o.VipName = &v
}

// GetVipPort returns the VipPort field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipPort() int64 {
	if o == nil || IsNil(o.VipPort) {
		var ret int64
		return ret
	}
	return *o.VipPort
}

// GetVipPortOk returns a tuple with the VipPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipPortOk() (*int64, bool) {
	if o == nil || IsNil(o.VipPort) {
		return nil, false
	}
	return o.VipPort, true
}

// IsSetVipPort returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipPort() bool {
	if o != nil && !IsNil(o.VipPort) {
		return true
	}

	return false
}

// SetVipPort gets a reference to the given int64 and assigns it to the VipPort field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipPort(v int64) {
	o.VipPort = &v
}

// GetVipSticky returns the VipSticky field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipSticky() string {
	if o == nil || IsNil(o.VipSticky.Get()) {
		var ret string
		return ret
	}
	return *o.VipSticky.Get()
}

// GetVipStickyOk returns a tuple with the VipSticky field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipStickyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipSticky.Get(), o.VipSticky.IsSet()
}

// IsSetVipSticky returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipSticky() bool {
	if o != nil && o.VipSticky.IsSet() {
		return true
	}

	return false
}

// SetVipSticky gets a reference to the given NullableString and assigns it to the VipSticky field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipSticky(v string) {
	o.VipSticky.Set(&v)
}

// SetVipStickyNil sets the value for VipSticky to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipStickyNil() {
	o.VipSticky.Set(nil)
}

// UnsetVipSticky ensures that no value is present for VipSticky, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipSticky() {
	o.VipSticky.Unset()
}

// GetVipBalance returns the VipBalance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipBalance() string {
	if o == nil || IsNil(o.VipBalance.Get()) {
		var ret string
		return ret
	}
	return *o.VipBalance.Get()
}

// GetVipBalanceOk returns a tuple with the VipBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipBalance.Get(), o.VipBalance.IsSet()
}

// IsSetVipBalance returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipBalance() bool {
	if o != nil && o.VipBalance.IsSet() {
		return true
	}

	return false
}

// SetVipBalance gets a reference to the given NullableString and assigns it to the VipBalance field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipBalance(v string) {
	o.VipBalance.Set(&v)
}

// SetVipBalanceNil sets the value for VipBalance to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipBalanceNil() {
	o.VipBalance.Set(nil)
}

// UnsetVipBalance ensures that no value is present for VipBalance, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipBalance() {
	o.VipBalance.Unset()
}

// GetServicePort returns the ServicePort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServicePort() string {
	if o == nil || IsNil(o.ServicePort.Get()) {
		var ret string
		return ret
	}
	return *o.ServicePort.Get()
}

// GetServicePortOk returns a tuple with the ServicePort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServicePortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServicePort.Get(), o.ServicePort.IsSet()
}

// IsSetServicePort returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetServicePort() bool {
	if o != nil && o.ServicePort.IsSet() {
		return true
	}

	return false
}

// SetServicePort gets a reference to the given NullableString and assigns it to the ServicePort field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServicePort(v string) {
	o.ServicePort.Set(&v)
}

// SetServicePortNil sets the value for ServicePort to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServicePortNil() {
	o.ServicePort.Set(nil)
}

// UnsetServicePort ensures that no value is present for ServicePort, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetServicePort() {
	o.ServicePort.Unset()
}

// GetSourceAddress returns the SourceAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSourceAddress() string {
	if o == nil || IsNil(o.SourceAddress.Get()) {
		var ret string
		return ret
	}
	return *o.SourceAddress.Get()
}

// GetSourceAddressOk returns a tuple with the SourceAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSourceAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceAddress.Get(), o.SourceAddress.IsSet()
}

// IsSetSourceAddress returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSourceAddress() bool {
	if o != nil && o.SourceAddress.IsSet() {
		return true
	}

	return false
}

// SetSourceAddress gets a reference to the given NullableString and assigns it to the SourceAddress field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSourceAddress(v string) {
	o.SourceAddress.Set(&v)
}

// SetSourceAddressNil sets the value for SourceAddress to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSourceAddressNil() {
	o.SourceAddress.Set(nil)
}

// UnsetSourceAddress ensures that no value is present for SourceAddress, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetSourceAddress() {
	o.SourceAddress.Unset()
}

// GetSslCert returns the SslCert field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslCert() GetAlerts200ResponseAllOfCheckGroupsInnerInstance {
	if o == nil || IsNil(o.SslCert) {
		var ret GetAlerts200ResponseAllOfCheckGroupsInnerInstance
		return ret
	}
	return *o.SslCert
}

// GetSslCertOk returns a tuple with the SslCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslCertOk() (*GetAlerts200ResponseAllOfCheckGroupsInnerInstance, bool) {
	if o == nil || IsNil(o.SslCert) {
		return nil, false
	}
	return o.SslCert, true
}

// IsSetSslCert returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSslCert() bool {
	if o != nil && !IsNil(o.SslCert) {
		return true
	}

	return false
}

// SetSslCert gets a reference to the given GetAlerts200ResponseAllOfCheckGroupsInnerInstance and assigns it to the SslCert field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslCert(v GetAlerts200ResponseAllOfCheckGroupsInnerInstance) {
	o.SslCert = &v
}

// GetSslMode returns the SslMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslMode() string {
	if o == nil || IsNil(o.SslMode.Get()) {
		var ret string
		return ret
	}
	return *o.SslMode.Get()
}

// GetSslModeOk returns a tuple with the SslMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslMode.Get(), o.SslMode.IsSet()
}

// IsSetSslMode returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSslMode() bool {
	if o != nil && o.SslMode.IsSet() {
		return true
	}

	return false
}

// SetSslMode gets a reference to the given NullableString and assigns it to the SslMode field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslMode(v string) {
	o.SslMode.Set(&v)
}

// SetSslModeNil sets the value for SslMode to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslModeNil() {
	o.SslMode.Set(nil)
}

// UnsetSslMode ensures that no value is present for SslMode, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetSslMode() {
	o.SslMode.Unset()
}

// GetSslRedirectMode returns the SslRedirectMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslRedirectMode() string {
	if o == nil || IsNil(o.SslRedirectMode.Get()) {
		var ret string
		return ret
	}
	return *o.SslRedirectMode.Get()
}

// GetSslRedirectModeOk returns a tuple with the SslRedirectMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSslRedirectModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SslRedirectMode.Get(), o.SslRedirectMode.IsSet()
}

// IsSetSslRedirectMode returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSslRedirectMode() bool {
	if o != nil && o.SslRedirectMode.IsSet() {
		return true
	}

	return false
}

// SetSslRedirectMode gets a reference to the given NullableString and assigns it to the SslRedirectMode field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslRedirectMode(v string) {
	o.SslRedirectMode.Set(&v)
}

// SetSslRedirectModeNil sets the value for SslRedirectMode to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSslRedirectModeNil() {
	o.SslRedirectMode.Set(nil)
}

// UnsetSslRedirectMode ensures that no value is present for SslRedirectMode, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetSslRedirectMode() {
	o.SslRedirectMode.Unset()
}

// GetVipShared returns the VipShared field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipShared() bool {
	if o == nil || IsNil(o.VipShared) {
		var ret bool
		return ret
	}
	return *o.VipShared
}

// GetVipSharedOk returns a tuple with the VipShared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipSharedOk() (*bool, bool) {
	if o == nil || IsNil(o.VipShared) {
		return nil, false
	}
	return o.VipShared, true
}

// IsSetVipShared returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipShared() bool {
	if o != nil && !IsNil(o.VipShared) {
		return true
	}

	return false
}

// SetVipShared gets a reference to the given bool and assigns it to the VipShared field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipShared(v bool) {
	o.VipShared = &v
}

// GetVipDirectAddress returns the VipDirectAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipDirectAddress() string {
	if o == nil || IsNil(o.VipDirectAddress.Get()) {
		var ret string
		return ret
	}
	return *o.VipDirectAddress.Get()
}

// GetVipDirectAddressOk returns a tuple with the VipDirectAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipDirectAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VipDirectAddress.Get(), o.VipDirectAddress.IsSet()
}

// IsSetVipDirectAddress returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipDirectAddress() bool {
	if o != nil && o.VipDirectAddress.IsSet() {
		return true
	}

	return false
}

// SetVipDirectAddress gets a reference to the given NullableString and assigns it to the VipDirectAddress field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipDirectAddress(v string) {
	o.VipDirectAddress.Set(&v)
}

// SetVipDirectAddressNil sets the value for VipDirectAddress to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipDirectAddressNil() {
	o.VipDirectAddress.Set(nil)
}

// UnsetVipDirectAddress ensures that no value is present for VipDirectAddress, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetVipDirectAddress() {
	o.VipDirectAddress.Unset()
}

// GetServerName returns the ServerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServerName() string {
	if o == nil || IsNil(o.ServerName.Get()) {
		var ret string
		return ret
	}
	return *o.ServerName.Get()
}

// GetServerNameOk returns a tuple with the ServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServerName.Get(), o.ServerName.IsSet()
}

// IsSetServerName returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetServerName() bool {
	if o != nil && o.ServerName.IsSet() {
		return true
	}

	return false
}

// SetServerName gets a reference to the given NullableString and assigns it to the ServerName field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServerName(v string) {
	o.ServerName.Set(&v)
}

// SetServerNameNil sets the value for ServerName to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServerNameNil() {
	o.ServerName.Set(nil)
}

// UnsetServerName ensures that no value is present for ServerName, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetServerName() {
	o.ServerName.Unset()
}

// GetPoolName returns the PoolName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetPoolName() string {
	if o == nil || IsNil(o.PoolName.Get()) {
		var ret string
		return ret
	}
	return *o.PoolName.Get()
}

// GetPoolNameOk returns a tuple with the PoolName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetPoolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PoolName.Get(), o.PoolName.IsSet()
}

// IsSetPoolName returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetPoolName() bool {
	if o != nil && o.PoolName.IsSet() {
		return true
	}

	return false
}

// SetPoolName gets a reference to the given NullableString and assigns it to the PoolName field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetPoolName(v string) {
	o.PoolName.Set(&v)
}

// SetPoolNameNil sets the value for PoolName to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetPoolNameNil() {
	o.PoolName.Set(nil)
}

// UnsetPoolName ensures that no value is present for PoolName, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetPoolName() {
	o.PoolName.Unset()
}

// GetRemoving returns the Removing field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetRemoving() bool {
	if o == nil || IsNil(o.Removing) {
		var ret bool
		return ret
	}
	return *o.Removing
}

// GetRemovingOk returns a tuple with the Removing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetRemovingOk() (*bool, bool) {
	if o == nil || IsNil(o.Removing) {
		return nil, false
	}
	return o.Removing, true
}

// IsSetRemoving returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetRemoving() bool {
	if o != nil && !IsNil(o.Removing) {
		return true
	}

	return false
}

// SetRemoving gets a reference to the given bool and assigns it to the Removing field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetRemoving(v bool) {
	o.Removing = &v
}

// GetVipSource returns the VipSource field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipSource() string {
	if o == nil || IsNil(o.VipSource) {
		var ret string
		return ret
	}
	return *o.VipSource
}

// GetVipSourceOk returns a tuple with the VipSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipSourceOk() (*string, bool) {
	if o == nil || IsNil(o.VipSource) {
		return nil, false
	}
	return o.VipSource, true
}

// IsSetVipSource returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipSource() bool {
	if o != nil && !IsNil(o.VipSource) {
		return true
	}

	return false
}

// SetVipSource gets a reference to the given string and assigns it to the VipSource field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipSource(v string) {
	o.VipSource = &v
}

// GetExtraConfig returns the ExtraConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExtraConfig() string {
	if o == nil || IsNil(o.ExtraConfig.Get()) {
		var ret string
		return ret
	}
	return *o.ExtraConfig.Get()
}

// GetExtraConfigOk returns a tuple with the ExtraConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExtraConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExtraConfig.Get(), o.ExtraConfig.IsSet()
}

// IsSetExtraConfig returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetExtraConfig() bool {
	if o != nil && o.ExtraConfig.IsSet() {
		return true
	}

	return false
}

// SetExtraConfig gets a reference to the given NullableString and assigns it to the ExtraConfig field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExtraConfig(v string) {
	o.ExtraConfig.Set(&v)
}

// SetExtraConfigNil sets the value for ExtraConfig to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExtraConfigNil() {
	o.ExtraConfig.Set(nil)
}

// UnsetExtraConfig ensures that no value is present for ExtraConfig, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetExtraConfig() {
	o.ExtraConfig.Unset()
}

// GetServiceAccess returns the ServiceAccess field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServiceAccess() string {
	if o == nil || IsNil(o.ServiceAccess.Get()) {
		var ret string
		return ret
	}
	return *o.ServiceAccess.Get()
}

// GetServiceAccessOk returns a tuple with the ServiceAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetServiceAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceAccess.Get(), o.ServiceAccess.IsSet()
}

// IsSetServiceAccess returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetServiceAccess() bool {
	if o != nil && o.ServiceAccess.IsSet() {
		return true
	}

	return false
}

// SetServiceAccess gets a reference to the given NullableString and assigns it to the ServiceAccess field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServiceAccess(v string) {
	o.ServiceAccess.Set(&v)
}

// SetServiceAccessNil sets the value for ServiceAccess to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetServiceAccessNil() {
	o.ServiceAccess.Set(nil)
}

// UnsetServiceAccess ensures that no value is present for ServiceAccess, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetServiceAccess() {
	o.ServiceAccess.Unset()
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetNetworkId() string {
	if o == nil || IsNil(o.NetworkId.Get()) {
		var ret string
		return ret
	}
	return *o.NetworkId.Get()
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkId.Get(), o.NetworkId.IsSet()
}

// IsSetNetworkId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetNetworkId() bool {
	if o != nil && o.NetworkId.IsSet() {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given NullableString and assigns it to the NetworkId field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetNetworkId(v string) {
	o.NetworkId.Set(&v)
}

// SetNetworkIdNil sets the value for NetworkId to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetNetworkIdNil() {
	o.NetworkId.Set(nil)
}

// UnsetNetworkId ensures that no value is present for NetworkId, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetNetworkId() {
	o.NetworkId.Unset()
}

// GetSubnetId returns the SubnetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSubnetId() string {
	if o == nil || IsNil(o.SubnetId.Get()) {
		var ret string
		return ret
	}
	return *o.SubnetId.Get()
}

// GetSubnetIdOk returns a tuple with the SubnetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetId.Get(), o.SubnetId.IsSet()
}

// IsSetSubnetId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetSubnetId() bool {
	if o != nil && o.SubnetId.IsSet() {
		return true
	}

	return false
}

// SetSubnetId gets a reference to the given NullableString and assigns it to the SubnetId field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSubnetId(v string) {
	o.SubnetId.Set(&v)
}

// SetSubnetIdNil sets the value for SubnetId to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetSubnetIdNil() {
	o.SubnetId.Set(nil)
}

// UnsetSubnetId ensures that no value is present for SubnetId, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetSubnetId() {
	o.SubnetId.Unset()
}

// GetExternalPortId returns the ExternalPortId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalPortId() string {
	if o == nil || IsNil(o.ExternalPortId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalPortId.Get()
}

// GetExternalPortIdOk returns a tuple with the ExternalPortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetExternalPortIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalPortId.Get(), o.ExternalPortId.IsSet()
}

// IsSetExternalPortId returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetExternalPortId() bool {
	if o != nil && o.ExternalPortId.IsSet() {
		return true
	}

	return false
}

// SetExternalPortId gets a reference to the given NullableString and assigns it to the ExternalPortId field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExternalPortId(v string) {
	o.ExternalPortId.Set(&v)
}

// SetExternalPortIdNil sets the value for ExternalPortId to be an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetExternalPortIdNil() {
	o.ExternalPortId.Set(nil)
}

// UnsetExternalPortId ensures that no value is present for ExternalPortId, not even an explicit nil
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnsetExternalPortId() {
	o.ExternalPortId.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// IsSetStatus returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetStatus(v string) {
	o.Status = &v
}

// GetVipStatus returns the VipStatus field value if set, zero value otherwise.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipStatus() string {
	if o == nil || IsNil(o.VipStatus) {
		var ret string
		return ret
	}
	return *o.VipStatus
}

// GetVipStatusOk returns a tuple with the VipStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) GetVipStatusOk() (*string, bool) {
	if o == nil || IsNil(o.VipStatus) {
		return nil, false
	}
	return o.VipStatus, true
}

// IsSetVipStatus returns a boolean if a field has been set.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) IsSetVipStatus() bool {
	if o != nil && !IsNil(o.VipStatus) {
		return true
	}

	return false
}

// SetVipStatus gets a reference to the given string and assigns it to the VipStatus field.
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) SetVipStatus(v string) {
	o.VipStatus = &v
}

func (o ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LoadBalancer) {
		toSerialize["loadBalancer"] = o.LoadBalancer
	}
	if o.Instance.IsSet() {
		toSerialize["instance"] = o.Instance.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.InternalId) {
		toSerialize["internalId"] = o.InternalId
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Sticky) {
		toSerialize["sticky"] = o.Sticky
	}
	if o.SslEnabled.IsSet() {
		toSerialize["sslEnabled"] = o.SslEnabled.Get()
	}
	if !IsNil(o.ExternalAddress) {
		toSerialize["externalAddress"] = o.ExternalAddress
	}
	if o.BackendPort.IsSet() {
		toSerialize["backendPort"] = o.BackendPort.Get()
	}
	if o.VipType.IsSet() {
		toSerialize["vipType"] = o.VipType.Get()
	}
	if !IsNil(o.VipAddress) {
		toSerialize["vipAddress"] = o.VipAddress
	}
	if o.VipHostname.IsSet() {
		toSerialize["vipHostname"] = o.VipHostname.Get()
	}
	if !IsNil(o.VipProtocol) {
		toSerialize["vipProtocol"] = o.VipProtocol
	}
	if o.VipScheme.IsSet() {
		toSerialize["vipScheme"] = o.VipScheme.Get()
	}
	if o.VipMode.IsSet() {
		toSerialize["vipMode"] = o.VipMode.Get()
	}
	if !IsNil(o.VipName) {
		toSerialize["vipName"] = o.VipName
	}
	if !IsNil(o.VipPort) {
		toSerialize["vipPort"] = o.VipPort
	}
	if o.VipSticky.IsSet() {
		toSerialize["vipSticky"] = o.VipSticky.Get()
	}
	if o.VipBalance.IsSet() {
		toSerialize["vipBalance"] = o.VipBalance.Get()
	}
	if o.ServicePort.IsSet() {
		toSerialize["servicePort"] = o.ServicePort.Get()
	}
	if o.SourceAddress.IsSet() {
		toSerialize["sourceAddress"] = o.SourceAddress.Get()
	}
	if !IsNil(o.SslCert) {
		toSerialize["sslCert"] = o.SslCert
	}
	if o.SslMode.IsSet() {
		toSerialize["sslMode"] = o.SslMode.Get()
	}
	if o.SslRedirectMode.IsSet() {
		toSerialize["sslRedirectMode"] = o.SslRedirectMode.Get()
	}
	if !IsNil(o.VipShared) {
		toSerialize["vipShared"] = o.VipShared
	}
	if o.VipDirectAddress.IsSet() {
		toSerialize["vipDirectAddress"] = o.VipDirectAddress.Get()
	}
	if o.ServerName.IsSet() {
		toSerialize["serverName"] = o.ServerName.Get()
	}
	if o.PoolName.IsSet() {
		toSerialize["poolName"] = o.PoolName.Get()
	}
	if !IsNil(o.Removing) {
		toSerialize["removing"] = o.Removing
	}
	if !IsNil(o.VipSource) {
		toSerialize["vipSource"] = o.VipSource
	}
	if o.ExtraConfig.IsSet() {
		toSerialize["extraConfig"] = o.ExtraConfig.Get()
	}
	if o.ServiceAccess.IsSet() {
		toSerialize["serviceAccess"] = o.ServiceAccess.Get()
	}
	if o.NetworkId.IsSet() {
		toSerialize["networkId"] = o.NetworkId.Get()
	}
	if o.SubnetId.IsSet() {
		toSerialize["subnetId"] = o.SubnetId.Get()
	}
	if o.ExternalPortId.IsSet() {
		toSerialize["externalPortId"] = o.ExternalPortId.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.VipStatus) {
		toSerialize["vipStatus"] = o.VipStatus
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *ListLoadBalancerVirtualServers200ResponseAllOfLoadBalancerInstancesInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
