/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.8
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetContacts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContacts200Response{}

// GetContacts200Response struct for GetContacts200Response
type GetContacts200Response struct {
	Contact              *ListContacts200ResponseAllOfContactsInner `json:"contact,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetContacts200Response GetContacts200Response

// NewGetContacts200Response instantiates a new GetContacts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContacts200Response() *GetContacts200Response {
	this := GetContacts200Response{}
	return &this
}

// NewGetContacts200ResponseWithDefaults instantiates a new GetContacts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContacts200ResponseWithDefaults() *GetContacts200Response {
	this := GetContacts200Response{}
	return &this
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *GetContacts200Response) GetContact() ListContacts200ResponseAllOfContactsInner {
	if o == nil || IsNil(o.Contact) {
		var ret ListContacts200ResponseAllOfContactsInner
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContacts200Response) GetContactOk() (*ListContacts200ResponseAllOfContactsInner, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// IsSetContact returns a boolean if a field has been set.
func (o *GetContacts200Response) IsSetContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given ListContacts200ResponseAllOfContactsInner and assigns it to the Contact field.
func (o *GetContacts200Response) SetContact(v ListContacts200ResponseAllOfContactsInner) {
	o.Contact = &v
}

func (o GetContacts200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContacts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}
func (o *GetContacts200Response) UnmarshalJSON(data []byte) (err error) {
	varGetContacts200Response := _GetContacts200Response{}

	err = json.Unmarshal(data, &varGetContacts200Response)

	if err != nil {
		return err
	}

	*o = GetContacts200Response(varGetContacts200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contact")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetContacts200Response struct {
	value *GetContacts200Response
	isSet bool
}

func (v NullableGetContacts200Response) Get() *GetContacts200Response {
	return v.value
}

func (v *NullableGetContacts200Response) Set(val *GetContacts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContacts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContacts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContacts200Response(val *GetContacts200Response) *NullableGetContacts200Response {
	return &NullableGetContacts200Response{value: val, isSet: true}
}

func (v NullableGetContacts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContacts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// - model_simple.mustache
