/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddJobsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddJobsRequest{}

// AddJobsRequest struct for AddJobsRequest
type AddJobsRequest struct {
	Job                  AddJobsRequestJob      `json:"job"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddJobsRequest AddJobsRequest

// NewAddJobsRequest instantiates a new AddJobsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddJobsRequest(job AddJobsRequestJob) *AddJobsRequest {
	this := AddJobsRequest{}
	this.Job = job
	return &this
}

// NewAddJobsRequestWithDefaults instantiates a new AddJobsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddJobsRequestWithDefaults() *AddJobsRequest {
	this := AddJobsRequest{}
	return &this
}

// GetJob returns the Job field value
func (o *AddJobsRequest) GetJob() AddJobsRequestJob {
	if o == nil {
		var ret AddJobsRequestJob
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *AddJobsRequest) GetJobOk() (*AddJobsRequestJob, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *AddJobsRequest) SetJob(v AddJobsRequestJob) {
	o.Job = v
}

func (o AddJobsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddJobsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job"] = o.Job

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddJobsRequest struct {
	value *AddJobsRequest
	isSet bool
}

func (v NullableAddJobsRequest) Get() *AddJobsRequest {
	return v.value
}

func (v *NullableAddJobsRequest) Set(val *AddJobsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddJobsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddJobsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddJobsRequest(val *AddJobsRequest) *NullableAddJobsRequest {
	return &NullableAddJobsRequest{value: val, isSet: true}
}

func (v NullableAddJobsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddJobsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (o *AddJobsRequest) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
