/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListSecurityGroupsInstance200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSecurityGroupsInstance200Response{}

// ListSecurityGroupsInstance200Response struct for ListSecurityGroupsInstance200Response
type ListSecurityGroupsInstance200Response struct {
	FirewallEnabled *bool `json:"firewallEnabled,omitempty"`
	// Array of security group objects
	SecurityGroups       []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner `json:"securityGroups,omitempty"`
	Success              *bool                                                           `json:"success,omitempty"`
	AdditionalProperties map[string]interface{}                                          `json:",remain"`
}

type _ListSecurityGroupsInstance200Response ListSecurityGroupsInstance200Response

// NewListSecurityGroupsInstance200Response instantiates a new ListSecurityGroupsInstance200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSecurityGroupsInstance200Response() *ListSecurityGroupsInstance200Response {
	this := ListSecurityGroupsInstance200Response{}
	return &this
}

// NewListSecurityGroupsInstance200ResponseWithDefaults instantiates a new ListSecurityGroupsInstance200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSecurityGroupsInstance200ResponseWithDefaults() *ListSecurityGroupsInstance200Response {
	this := ListSecurityGroupsInstance200Response{}
	return &this
}

// GetFirewallEnabled returns the FirewallEnabled field value if set, zero value otherwise.
func (o *ListSecurityGroupsInstance200Response) GetFirewallEnabled() bool {
	if o == nil || IsNil(o.FirewallEnabled) {
		var ret bool
		return ret
	}
	return *o.FirewallEnabled
}

// GetFirewallEnabledOk returns a tuple with the FirewallEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSecurityGroupsInstance200Response) GetFirewallEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.FirewallEnabled) {
		return nil, false
	}
	return o.FirewallEnabled, true
}

// IsSetFirewallEnabled returns a boolean if a field has been set.
func (o *ListSecurityGroupsInstance200Response) IsSetFirewallEnabled() bool {
	if o != nil && !IsNil(o.FirewallEnabled) {
		return true
	}

	return false
}

// SetFirewallEnabled gets a reference to the given bool and assigns it to the FirewallEnabled field.
func (o *ListSecurityGroupsInstance200Response) SetFirewallEnabled(v bool) {
	o.FirewallEnabled = &v
}

// GetSecurityGroups returns the SecurityGroups field value if set, zero value otherwise.
func (o *ListSecurityGroupsInstance200Response) GetSecurityGroups() []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner {
	if o == nil || IsNil(o.SecurityGroups) {
		var ret []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner
		return ret
	}
	return o.SecurityGroups
}

// GetSecurityGroupsOk returns a tuple with the SecurityGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSecurityGroupsInstance200Response) GetSecurityGroupsOk() ([]ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner, bool) {
	if o == nil || IsNil(o.SecurityGroups) {
		return nil, false
	}
	return o.SecurityGroups, true
}

// IsSetSecurityGroups returns a boolean if a field has been set.
func (o *ListSecurityGroupsInstance200Response) IsSetSecurityGroups() bool {
	if o != nil && !IsNil(o.SecurityGroups) {
		return true
	}

	return false
}

// SetSecurityGroups gets a reference to the given []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner and assigns it to the SecurityGroups field.
func (o *ListSecurityGroupsInstance200Response) SetSecurityGroups(v []ListSecurityGroupsInstance200ResponseAllOfSecurityGroupsInner) {
	o.SecurityGroups = v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ListSecurityGroupsInstance200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSecurityGroupsInstance200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// IsSetSuccess returns a boolean if a field has been set.
func (o *ListSecurityGroupsInstance200Response) IsSetSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ListSecurityGroupsInstance200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o ListSecurityGroupsInstance200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSecurityGroupsInstance200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirewallEnabled) {
		toSerialize["firewallEnabled"] = o.FirewallEnabled
	}
	if !IsNil(o.SecurityGroups) {
		toSerialize["securityGroups"] = o.SecurityGroups
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListSecurityGroupsInstance200Response struct {
	value *ListSecurityGroupsInstance200Response
	isSet bool
}

func (v NullableListSecurityGroupsInstance200Response) Get() *ListSecurityGroupsInstance200Response {
	return v.value
}

func (v *NullableListSecurityGroupsInstance200Response) Set(val *ListSecurityGroupsInstance200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSecurityGroupsInstance200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSecurityGroupsInstance200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSecurityGroupsInstance200Response(val *ListSecurityGroupsInstance200Response) *NullableListSecurityGroupsInstance200Response {
	return &NullableListSecurityGroupsInstance200Response{value: val, isSet: true}
}

func (v NullableListSecurityGroupsInstance200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSecurityGroupsInstance200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (o *ListSecurityGroupsInstance200Response) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
